### ISSUE TITLE
Problems with ls

### ISSUE THREAD

**Issue by ale5000-git** [rmyorston/busybox-w32#101]
Using "ls" on C:/ cause this (also when run as administrator):
```
ls: ./hiberfil.sys: Permission denied
ls: ./pagefile.sys: Permission denied
ls: ./swapfile.sys: Permission denied
```

It shouldn't need anything special just to list filenames.

Also using "busybox ls" on "C:/WINDOWS/system32" seems to freeze.
Maybe it do other things beside listing filenames that cause slowdown?

**Comment by rmyorston** [comment]
Yes, I see the problem with the ```sys``` files. They seem to have the 'hidden' and 'system' attributes, though I don't know why that would make any difference. I'll look into the issue later.

I don't have any problem with ```ls``` on "C:/WINDOWS/system32" in my Windows 8.1 installation. Again, I'll investigate this more later.

**Comment by ale5000-git** [comment]
I have tried to create a file with system and hidden attribute and it work properly.
Probably the problem is that the files are "in use", so I think that ls actually try to open the files instead of only look at filenames.

**Comment by rmyorston** [comment]
```ls``` calls ```lstat(2)``` on each file but the busybox-w32 implementation failed when the file was in use by another process. If this happens try a different API to get the file attributes.

I've tried ```ls C:/Windows/System32``` on a 64-bit Windows 10 system and it works there too.  It takes a few seconds the first time but after that it's quick.

**Comment by ale5000-git** [comment]
Thanks.

Is it possible, as optimization, to skip the execution of `lstat` if the parameters of `ls` doesn't ask for any file info?

**Comment by rmyorston** [comment]
That is slow. On my machines it takes about 10 seconds the first time.

Currently ```ls``` calls ```lstat``` or ```stat``` on every path it might need to display. Some sort of test  seems necessary because even though a filename might appear in a directory or might have been provided on the command line there's still the possibility that it can't be accessed. Consider:
```
$ ls file_that_does_not_exist
ls: file_that_does_not_exist: No such file or directory
```
We really don't want to skip a test here. Also note that in the default case of listing files to the console the file attributes are needed to determine how the filename should be coloured in the output.

The implementations of ```lstat``` and ```stat``` in busybox-w32 have one feature that slows them down compared to their equivalents on *NIX systems: files that don't have one of the standard extensions that indicate an executable on Windows are opened and read to see if they might be a shell script. Since Windows files don't have an 'executable' attribute this is how the busybox-w32 shell knows that a file is a shell script and how ```ls``` knows to colour shell scripts as executables.

A huge number of the files in C:/Windows/System32 are DLLs: over 2000 in my installations. As things stand each of these is being opened to check if it's a shell script when there's clearly no need to do so.

[This executable](https://frippery.org/files/busybox/busybox_stat.exe) avoids opening DLLs. It speeds up ```ls c:/windows/system32``` considerably on my system. Please try it.

**Comment by ale5000-git** [comment]
The linked version take about 3 seconds.

**Comment by rmyorston** [comment]
Thanks for testing that. I've committed the fix.

**Comment by ale5000-git** [comment]
Now it works fine, thanks.
