### ISSUE TITLE
Save help of applets

### ISSUE THREAD

**Issue by ale5000-git** [rmyorston/busybox-w32#107]
It was trying to save the help of applets but I noticed that the help is outputted to stderr instead of stdout.
Is it intended?

I have come up with this:
> busybox --list | while read APPLET_NAME; do
>   if [[ -z "$APPLET_NAME" ]]; then continue; fi
>   busybox --help "$APPLET_NAME" 2> "man/${APPLET_NAME}.manpage"
> done

Is there a better way?

**Comment by rmyorston** [comment]
It must be intentional because that's what it does. It's the same in upstream BusyBox. Other utilities on Linux output to stdout so BusyBox is inconsistent here.

Your script seems reasonable.

Building BusyBox generates a man page for the given configuration. I don't seem to be able to attach it to this issue so I've put a gzipped cat-format copy [here](https://frippery.org/files/busybox/busybox.1.gz).

**Comment by ale5000-git** [comment]
Thanks.

Could you please link the auto-generated man page when you update the binary builds in this page `https://frippery.org/busybox/`?

**Comment by rmyorston** [comment]
> Could you please link the auto-generated man page when you update the binary builds

Yeah, sure. I'll add this to my build/deploy script.
