### ISSUE TITLE
kill command doesn't work

### ISSUE THREAD

**Issue by nagkyo** [rmyorston/busybox-w32#118]
I built BusyBox v1.29.0 git to use win10 but I failed to use kill command like below.
I also confirmed that kill command works on BusyBox v1.28.0.git which I had built last year.

Outputs of ps command differ between the BusyBox versions. 
But I'm not sure of the root cause.  Does anyone have 
any suggestions or  is it possible to fix the issue?
 
=========================================
BusyBox v1.29.0.git (2018-06-16 12:29:07 JST) multi-call binary

C:/ $ ps | head -1 && ps | grep 'chrome'
PID   PPID  TIME  ELAPSED COMMAND
 7824  8040  0:40 35:23   chrome.exe
  684  7824  0:00 35:23   chrome.exe
 7532   684  0:00 35:23   chrome.exe
 9284  7824  0:19 35:23   chrome.exe
 2972  7824  0:02 35:22   chrome.exe
 7616  7824  0:00 35:22   chrome.exe
 3644  7824  0:45 15:57   chrome.exe
 9684  7824  0:01  2:14   chrome.exe
C:/ $
C:/ $ killall chrome.exe
killall: can't kill pid 7824: Function not implemented
killall: can't kill pid 684: Function not implemented
killall: can't kill pid 7532: Function not implemented
killall: can't kill pid 9284: Function not implemented
killall: can't kill pid 2972: Function not implemented
killall: can't kill pid 7616: Function not implemented
killall: can't kill pid 3644: Function not implemented
killall: can't kill pid 9684: Function not implemented

=========================================
BusyBox v1.28.0.git (2017-08-24 09:38:34 JST) multi-call binary

C:/ $ ps | head -1 && ps | grep 'chrome'
PID   COMMAND
 7824 chrome.exe
  684 chrome.exe
 7532 chrome.exe
 9284 chrome.exe
 2972 chrome.exe
 7616 chrome.exe
 3644 chrome.exe
 9684 chrome.exe
C:/ $

**Comment by rmyorston** [comment]
Since you built your binary last year there have been some changes to the implementation of the ```kill``` system call. Before 2017-09-27 ```kill``` always used the WIN32 function ```TerminateProcess``` to kill its target. In Unix terms this is like doing ```kill -9``` whereas the ```kill``` command should default to using the less brutal ```TERM``` signal.

Since 2017-09-27 busybox-w32 allows both the ```KILL``` and ```TERM``` signals to be sent to the taget. However, the code to implement ```TERM``` only works if the process performing the kill and its target are using the same architecture. If your BusyBox binary is 32-bit and Chrome is 64-bit you'll get the failure you've described.
 
There are a couple of workarounds:
- Use ```kill -9``` or ```kill -KILL``` to use the old, more effective kill code.
- Build a 64-bit version of BusyBox.

It's unfortunate that ```TERM``` doesn't work for processes with different architectures but the advantages of the new implementation probably outweigh the downsides. I might change the error code from 'Function not implemented' to 'Permission denied', which is slightly more accurate though not necessarily any more helpful.

**Comment by nagkyo** [comment]
Thank you so much for providing explanation and workarounds.
Yes, I use 32-bit version of BusyBox and 64-bit version of Chrome on Win 10 and found the failure.

Your support is greatly appreciated. I came to fully understand the root cause.
I confirmed that kill -9 command works on BusyBox  v1.29.0.git (32-bit) to Chrome (64-bit)
and kill command works on BusyBox v1.29.0.git (64-bit) to Chrome (64-bit).
