### ISSUE TITLE
ssl_client: write error: Broken pipe

### ISSUE THREAD

**Issue by ale5000-git** [rmyorston/busybox-w32#123]
I run this commands:
```
busybox ash
wget 'https://github.com/someone755/kerneller/raw/9bb15ca2e73e8b81e412d595b52a176bdeb7c70a/extract/tools/keycheck'
```

And I get:
`ssl_client: write error: Broken pipe`

There wasn't in the old version of BusyBox.

**Comment by rmyorston** [comment]
```wget``` has supported HTTPS URLs since FRP-1986-g701cea96c.

It seems that the error message is issued on 64-bit versions of Windows but not 32-bit versions. In either case the file is downloaded correctly.

**Comment by ale5000-git** [comment]
It is strange because if I run with `busybox wget` then the problems does NOT happen but it happen when using `wget` alone

**Comment by rmyorston** [comment]
Some more information on this.  The URL you mention above redirects to raw.githubusercontent.com. ```wget``` stops reading headers from github.com once it's collected the information it needs to perform the redirection. The child ```ssl_client``` process still has data it wants to pass to ```wget``` but it can't because ```wget``` has closed the pipe.  Hence the error.

I can make the error go away, but it requires adding code.

And even if I fix this particular case there are others: if the file to be downloaded already exists you get the same write error because ```wget``` stops reading from ```ssl_client``` once it's detected that.

**Comment by rmyorston** [comment]
Well, goodness me, yes it does. The 'broken pipe' message is no longer displayed.

**Comment by ale5000-git** [comment]
Good, thanks.
