### ISSUE TITLE
unzip -l discrepancies

### ISSUE THREAD

**Issue by ale5000-git** [rmyorston/busybox-w32#130]
I'm not sure where is the problem but using `unzip -l file.zip` on an **Italian** Windows PC I get:
`       72  02-29-2008 03:33   META-INF/com/google/android/updater-script`

Instead under Travis CI (so under Linux) I get:
`       72  2008-02-29 02:33   META-INF/com/google/android/updater-script`

The date order and also the timezone are different.
Is it possible to have them equal?

**Comment by rmyorston** [comment]
How is Travis CI doing that? It's possible it has its own unzip code.

Using unzip 6.0 on Linux I get the same output as busybox-w32.

**Comment by ale5000-git** [comment]
I have setup a test project.

You can see Travis CI log here: https://travis-ci.com/a5k-testing/unzip-test/builds/96193616
And then you can download this to test under Windows: https://github.com/a5k-testing/unzip-test/archive/master.zip

Probably busybox unzip use the system internationalization settings to display date, in this case the problem isn't directly here but in upstream BusyBox.
Since I want to compare the output of unzip -l of a zip on various systems probably I should ask upstream BusyBox to display the date of unzip -l in a common format like YYYY-MM-DD.

**Comment by rmyorston** [comment]
I still don't know what Travis CI is doing to display dates in YYYY-MM-DD format. This is inconsistent with BusyBox and Info-ZIP.

The output from BusyBox unzip matches that of Info-ZIP unzip. Both are hardcoded to display dates as DD-MM-YYYY. Info-ZIP allows the format to be changed at build-time but the default on *NIX is still DD-MM-YYYY.

Because the date format is hardcoded neither BusyBox unzip nor Info-ZIP unzip respect system internationalisation settings.

Dates and times in zip files are stored as local times. They can optionally also be stored as *NIX timestamps in UTC. In that case Info-ZIP uses the UTC time and the user's TZ setting to display the date/time. BusyBox doesn't do that.

**Comment by ale5000-git** [comment]
I'm not sure, maybe the Ubuntu packages for zip/unzip are different from standard Info-ZIP zip/unzip.

**Comment by rmyorston** [comment]
I've checked the source package: Debian (and hence Ubuntu) build unzip with a non-default option to display dates in ISO format.

Until either Info-ZIP or upstream BusyBox changes their default I'm unwilling to go it alone in busybox-w32.

**Comment by ale5000-git** [comment]
Thanks, I will try to ask upstream.
I'm closing for now.
