### ISSUE TITLE
Paste problem

### ISSUE THREAD

**Issue by ale5000-git** [rmyorston/busybox-w32#135]
I was trying to paste "~" inside busybox ash but it doesn't work instead it works in the Windows command prompt (using right click of the mouse and then clicking on Paste).

**Comment by ale5000-git** [comment]
If I copy `F~F` it got pasted as `FF`.
My Windows is in Italian, the codepage of the command prompt is 850 (as returned by chcp command1.)

**Comment by rmyorston** [comment]
Nope, I still don't see it. My Windows is US but configured for en_GB and with codepage 850.

When testing this I did spot a different issue: pasted text wasn't being displayed in ```vi``` until the user typed a character. This has been fixed in commit 19f7732.

**Comment by ale5000-git** [comment]
I have 64-bit Windows, keyboard is it_IT.

The first 30 charachter of the ASCI table are also ignored, these: `☺☻♥♦♣♠•◘○◙♂♀♪♫☼►◄↕‼¶§▬↨↑↓→←∟↔▲▼`

**Comment by rmyorston** [comment]
Control characters are filtered by the code to handle line editing. Some cause actions to happen and the rest are just ignored. None is passed to the shell.

Tilde is different, though. It would be interesting to know what happens when you paste a tilde character. Can you build busybox-w32 with some debug in ```read_key()``` in win32/termios.h? Just after the lines:
```
        if (record.EventType != KEY_EVENT)
            continue;
```
add this:
```
if (!record.Event.KeyEvent.bKeyDown)
    fprintf(stderr, "ASCII %02x virtual %04x state %04lx\n",
        record.Event.KeyEvent.uChar.AsciiChar,
        record.Event.KeyEvent.wVirtualKeyCode,
        record.Event.KeyEvent.dwControlKeyState);
```
When I do this on my system I get this output when pasting a tilde:
```
ASCII 7e virtual 00de state 0010
```
The virtual key 00de has the symbolic name ```VK_OEM_7```, so it's some sort of system-specific key, and the state 0010 corresponds to ```SHIFT_PRESSED```. If you check the [UK keyboard layout](https://en.wikipedia.org/wiki/British_and_American_keyboards) you'll see that tilde obtained as shift-#, just next to the return key.

Apparently tilde doesn't appear in the [Italian keyboard layout](https://superuser.com/questions/667622/italian-keyboard-entering-the-tilde-and-backtick-characters-without-cha), so I've no idea how it will be represented in ```read_key()```.

**Comment by ale5000-git** [comment]
Yes, I can build it but only when I'm at home; so it need time since most of the time I'm not at home.

**Comment by ale5000-git** [comment]
Apparently the test version fix also the paste problem.

Pasting tilde with IT keybard:
```
ASCII 00 virtual 0061 state 0002
ASCII 00 virtual 0062 state 0002
ASCII 00 virtual 0066 state 0002
ASCII 7e virtual 0012 state 0000
~
```

Pasting tilde with EN keybard:
```
~ASCII 7e virtual 00c0 state 0010
ASCII 00 virtual 0010 state 0000
```

And for pasting backtick with IT keybard:
```
ASCII 00 virtual 0069 state 0002
ASCII 00 virtual 0066 state 0002
ASCII 60 virtual 0012 state 0000
`
```

**Comment by rmyorston** [comment]
That all seems to make sense, except for the bit about pasting tilde working now. Adding debug shouldn't have fixed the problem.

That aside, the correct ASCII code is being reported for each character, apart from € which isn't present in codepage 850.

**Comment by ale5000-git** [comment]
About € it depends.

Quote:

> In 1998, code page 858 was derived from this code page by changing code point 213 (D5hex) from a dotless i ‹ı› to the euro sign ‹€›.[5] Despite this, IBM's PC DOS 2000, released in 1998, changed their definition of code page 850 to what they called modified code page 850 now including the euro sign at code point 213 instead of adding support for the new code page 858

**Comment by ale5000-git** [comment]
If I run `chcp 858` in busybox_test and then past the € symbol, then I get:
```
iASCII d5 virtual 0035 state 0009
ASCII 00 virtual 0012 state 0100
```

**Comment by rmyorston** [comment]
Never mind BusyBox, can you paste € into a Command Prompt?

I'm unable even to type € in a Command Prompt window. Neither AltGr4 (the usual way to enter € with a UK keyboard) nor Alt213 work.

**Comment by ale5000-git** [comment]
I have found the cause, it is the font.
I have right-clicked in the Windows command prompt and in the settings choosed "Lucida Console" as character type, then the € symbol started working on both codepage 850 and 858.

But in Busybox it is still:

Tabella codici attiva: 858
```
iASCII d5 virtual 0035 state 0009
ASCII 00 virtual 0012 state 0100
```

Tabella codici attiva: 850
```
?ASCII 3f virtual 0035 state 0009
ASCII 00 virtual 0012 state 0100
```

**Comment by rmyorston** [comment]
Here's my latest thinking on the euro issue.

The console in Microsoft Windows has a code page. In fact it has two, one for input and one for output, though they're normally the same. These are sometimes referred to as OEM code pages. Since just two code pages isn't complicated enough Microsoft also use a different, supposedly more portable (though not really), code page for stuff like filenames and text files generated by Notepad. These are referred to as ANSI code pages.

For Western European languages the OEM code page is 850 (or 858 with the €) and the ANSI code page is 1252. Other regions have different pairs of OEM and ANSI code pages.

busybox-w32 accepts input from the console in the OEM encoding, converts it to ANSI for internal use
(so that filenames work) and converts back to the OEM encoding when writing text to the console. This was all set up years ago as a result of issue #17.

Code page 850 doesn't have the € symbol so when one is entered ```read_key()``` is presented with a ? instead. Code page 858 does support the € and ```read_key()``` gets a character with hex value d5 which it passes to ```OemToCharBuff()``` for conversion to ANSI. Unfortunately this function doesn't seem to have got the memo about the euro so it tries to convert it to the 'i without a dot' that got thrown out when the € was introduced. Because 'i without a dot' isn't in code page 1252 it's replaced by the next best thing, 'i with a dot'.

I could bodge ```read_key()``` to do the correct conversion, but the reverse conversion is broken too so I'd have to change the output routines as well.

I don't know what dark magic cmd.exe is using to read the € in code page 850. I guess that in code page 858 it just skips the OEM->ANSI->OEM round trip that busybox-w32 uses, thus avoiding the broken conversion.

**Comment by ale5000-git** [comment]
Why not using utf-8 internally? (so OEM->UTF-8->OEM)
The first 128 chars will still use 1 byte (so no waste in this case) and the others will use more space but at least they will be represented correctly.

This will probably fix also future problems.

**Comment by rmyorston** [comment]
>Why not using utf-8 internally?

Lots of reasons.

* I don't control which ANSI code page everybody else uses
* Support for UTF-8 in Windows has historically been very broken (though it's getting better)
* Upstream BusyBox has trouble with UTF-8 (try BusyBox ```vi``` in a UTF-8 locale)

**Comment by rmyorston** [comment]
It took a bit of work to sort out, but commit 93a6380 adds support for entering and displaying the € symbol. Some notes:

* It only works for OEM code page 858.
* When busybox-w32 is run in a console with OEM code page 850 it automatically changes it to 858.
* To enter the € symbol using the Alt key it's necessary to use the ANSI (not OEM) character code: Alt0128.

There's a new binary on my website: [busybox_euro.exe](https://frippery.org/files/busybox/busybox_euro.exe). Does it work for you? Does it fix the issue with pasting tilde?

**Comment by ale5000-git** [comment]
Paste euro, tilde and backtick work perfectly now, thanks :+1: 

There is only a minor inconsistency, when you enter inside ash it change codepage from 850 to 858 but when you exit it leave the changed codepage (858) in the Windows command prompt.
It isn't a great problem but one might not expect that when running from a bat file.
