### ISSUE TITLE
Bring back symlink code

### ISSUE THREAD

**Issue by ale5000-git** [rmyorston/busybox-w32#142]
Since the "implement readlink(2)" change it may be good to bring back this code: https://github.com/rmyorston/busybox-w32/commit/6312c005522de47dcaf442f613065415bcbd8ef7

**Comment by rmyorston** [comment]
No, that code is about creating symlinks, which still isn't implemented.

**Comment by ale5000-git** [comment]
Isn't `CreateSymbolicLinkA` enough for this? https://docs.microsoft.com/en-us/windows/desktop/api/winbase/nf-winbase-createsymboliclinka

PS: The Unicode version and "\?" is needed for longer pathes.

**Comment by rmyorston** [comment]
Yes, except that it requires Administrator privileges (or a recent version of Windows 10 with Developer Mode enabled and the application passes a magic flag to the function).

Rather than surprise and disappoint people who expect symlinks to Just Work busybox-w32 has never supported their creation.

**Comment by ale5000-git** [comment]
Not administrator right, just SeCreateSymbolicLinkPrivilege privilege that by default is only enabled for Administrators but can be changed.

Ref: https://superuser.com/questions/124679/how-do-i-create-a-link-in-windows-7-home-premium-as-a-regular-user

Can the code just check for this privilege and enable/disable code symlink creation accordingly?

**Comment by rmyorston** [comment]
>can be changed

Which means it doesn't Just Work. The code *could* check for the privilege but if people don't enable it it's just bloat.

Not *entirely* unrelated is 0533794af and [busybox_su.exe](https://frippery.org/files/busybox/busybox_su.exe).

**Comment by ale5000-git** [comment]
Well busybox is a command line tool, people that use it should have at least a minimal knowledge.

In my opinion to do it in the simplest way possible the code could do in this order:
- Check if it is Windows 10 with developer mode enabled (not sure how) and create symlink immediately
- Check if the SeCreateSymbolicLinkPrivilege is granted and also in this case create symlink immediately
- Use the new su code to ask admin permissions and create the symlink in the new window (but possibly create a hidden console so the user just see the User Account Control prompt)

---------------------------------------------

About the su code my suggestion is to change the default folder to the same folder it was before; since it now start in the C:/Windows/system32 folder image what bad things will happen if someone use `su -c "rm -r *"`.

**Comment by rmyorston** [comment]
>people that use it should have at least a minimal knowledge.

It depends on what kind of people are using busybox-w32. Some might be *nix command line junkies, though that doesn't mean they know about the minutiae of setting Windows policy. Increasingly, though, I'm seeing projects that include or suggest downloading busybox-w32. The authors of these projects may have a detailed knowledge of the *nix command line and Windows but their users may not. See, for example, [emax64](https://github.com/m-parashar/emax64), [nogui](https://github.com/myfreeer/nogui) and [plugin.program.xmltv.meld](https://github.com/primaeval/plugin.program.xmltv.meld).

A great advantage of busybox-w32 is that it can be dropped in without requiring any configuration by the end user.

>the simplest way possible (for the user)

Pleased to note that you added 'for the user', as what you suggest certainly isn't the simplest way possible for the busybox-w32 developer. I'm not going to even attempt to implement that: the first two items are, I suggest, unnecessary bloat for most users. The third, using ```su```, is far too heavyweight to use in an implementation of ```symlink(2)```.

**Comment by rmyorston** [comment]
>my suggestion is to change the default folder to the same folder it was before

That was the intention, and in my testing that's how ```su``` behaved.

>it now start in the C:/Windows/system32 folder

You've installed busybox-w32 in C:/Windows/system32, haven't you? I have it in my current directory.

According to the documentation if the directory name is set to a NULL pointer the new process is started in the same directory as its parent. That's how I'm calling ```ShellExecuteEx()``` and that's the behaviour I'm seeing.

If the binary is installed in C:/Users/rmy or C:/usr/bin it works as documented. If it's installed in C:/Windows or C:/Windows/System32 the new process has C:/Windows/System32 as its current directory. If it's in C:/Windows/whatever (that's literally what I tried) it works as documented and the child has the same directory as its parent.

Setting the directory explicitly in the call to ```ShellExecuteEx()``` doesn't help.

Thank you, Microsoft.

I can workaround this by passing the parent's current directory to the shell, but it's annoying to have to do this because of some weird, undocumented behaviour of the Windows API.

**Comment by ale5000-git** [comment]
Yes, currently I have installed busybox-w32 in C:/Windows/system32 for simplicity, this MS behaviour is annoying.

About symlink there is also a simple solution: if SeCreateSymbolicLinkPrivilege privilege is granted do it otherwise always fail with a custom error code.
In this way I can workaround failures in my script and users not knowning it will not even notice it.

**Comment by rmyorston** [comment]
In [this](https://stackoverflow.com/questions/38033790/shellexecute-a-cmd-prompt-with-a-specific-working-directory) Stack Overflow question it is claimed:

>Microsoft added this as a security feature starting in Windows 8. Whenever cmd.exe detects it's running elevated, it ignores its launch parameters and always starts in %SystemRoot%\System32. You cannot override this behavior.

Maybe the same applies to all binaries in certain directories. Seems like a pretty useless security feature.

Anyway, here's a new binary that behaves as intended, despite Microsoft's interference: [busybox_su2.exe](https://frippery.org/files/busybox/busybox_su2.exe).

**Comment by ale5000-git** [comment]
I suppose (just my supposition) they do it to avoid possible exploits using specially crafted parameters, but there are certainly better way to avoid it.

It now works correctly but I would like if possible a parameter to automatically exit when done from the elevated prompt (for automate things).

**Comment by ale5000-git** [comment]
Talked too early, work from a local disk but not from a network folder, in this case still use C:/Windows/System32

![busybox-with-nas-folder-as-current-folder](https://user-images.githubusercontent.com/15793015/54032941-4c813b80-41b3-11e9-9365-4098396d1fcb.png)

**Comment by rmyorston** [comment]
>automatically exit when done

Can you use something like the example from the commit message (without the ```read```, if you like)?

>su -c "ls -l; read -p 'Hit return to exit: '; exit"

---

>works from a local disk but not from a network folder

I don't know what's going on there. Can you manually ```cd``` to the network folder from the ```su``` elevated prompt?

**Comment by rmyorston** [comment]
[busybox_su3.exe](https://frippery.org/files/busybox/busybox_su3.exe) prints a message in the ```su``` console if it fails to change directory.

**Comment by ale5000-git** [comment]
```
chdir(//nas326/pc) failed No such file or directory
C:/Windows/system32 $
```

Probably it need backslash for network folders.

**Comment by rmyorston** [comment]
OK, what if i revert 585d17d26 (win32: canonicalize path in chdir(2)). That calls ```realpath(3)``` on the directory name which is supposed to remove duplicated slashes, which are unnecessary in the *nix world. [busybox_su4.exe](https://frippery.org/files/busybox/busybox_su4.exe).

**Comment by ale5000-git** [comment]
@rmyorston: This revert fix the case 1 (so we are a step ahead) but not the case 2 where the executable itslef is on a network folder.

**Comment by rmyorston** [comment]
Close. What my implementation of ```realpath(3)``` actually does to a network folder is leave it with a ```UNC/``` prefix. This is one of the things that ```normalize_ntpath()``` from Git for Windows fixes up.

**Comment by rmyorston** [comment]
I've added a ```normalize_ntpathA()``` function, have used it in ```realpath(3)``` and have restored canonicalization in ```chdir(2)```. Try [busybox_su5.exe](https://frippery.org/files/busybox/busybox_su5.exe)

**Comment by ale5000-git** [comment]
Same as busybox_su4.exe:
Case 1) OK
Case 2) Unable to run su

Dividing case 2:
2a) `\\nas326\pc>busybox_su55.exe su` => It cannot find itself
2b) `C:\>\\nas326\pc\busybox_su5.exe su` => It cannot find itself
2c) `C:\>\\nas326\pc\busybox_su5.exe` => OK

**Comment by rmyorston** [comment]
I'm happy with the fix to case 1. I'll commit that.

Case 2 looks like a problem with ```ShellExecuteEx()```. If you replace ```su``` with any other BusyBox applet, such as ```ls```, it'll work. In that case the binary from the network folder is being run by ```spawnve```. It's only when ```ShellExecuteEx()``` is asked to run the same binary that it fails.

It's possible there's nothing we can do about that. If the issue is limited to running ```su``` from a binary in a network folder we might just have to document it and live with it.

**Comment by ale5000-git** [comment]
I'm not sure but isn't possible that also the function `get_busybox_exec_path` need `normalize_ntpathA`?

**Comment by ale5000-git** [comment]
@rmyorston

Actually the problem is another, try to:
- Open a command prompt already as administrator
- `cd` to a network folder with `busybox_su5.exe`
- use `ls` to verify that the file is already here
- run `busybox_su5.exe` and it return `ash: busybox_su5.exe: not found`.
Really strange.

![busybox-as-admin-problem](https://user-images.githubusercontent.com/15793015/54049761-b3b3e580-41dd-11e9-92c9-caa724efbc65.png)

**Comment by rmyorston** [comment]
```get_busybox_exec_path``` is fine. It seems that only the output of *some* functions needs normalisation.

As for the second issue, if the network folder isn't on ```PATH``` you'll need to use ```./busybox_su5.exe``` to run it.

**Comment by rmyorston** [comment]
Got it!

It seems that to run a binary with a UNC path ```ShellExecuteEx()``` requires **backslashes** as the path separator.

**Comment by ale5000-git** [comment]
Well, I don't know why but I never remember that `.` isn't included by default in busybpx as in Windows :(

**Comment by rmyorston** [comment]
Here's a new binary from current master: [busybox_su6.exe](https://frippery.org/files/busybox/busybox_su6.exe). I've removed the old ones.

The new one:
- fixes the problem ```su``` had running binaries with UNC paths;
- changes the shell prompt and window title in the ```su``` window.

**Comment by ale5000-git** [comment]
Thanks it works perfectly now and I also like the new ash options to change folder and title :)

There are just minor display issues (no functional problems):
- `$` is now `#` in an elevated prompt but probably it is intended
- `~/` become `C:/Users/Ale/` in an elevated prompt, is it intended?
- `//ca/LANTEST` became `~/ca/LANTEST` in an elevated prompt, I think this isn't intended

**Comment by rmyorston** [comment]
I won't be sending a patch for the new ash options to upstream BusyBox. They'll remain non-portable oddities in busybox-w32 (until I can find a way of removing them, just to inconvenience anyone who's unwise enough to use them.).

On the display issues:

- The ```$```/```#``` thing is how normal and root users have been distinguished in *nix since forever, so that's certainly intended.

- ```~/``` becoming ```C:/Users/Ale/``` was intentional. ```su``` on *nix really does make you root so your home directory changes to root's. Since, for brevity, the home directory is represented as ```~``` in the command prompt and since root's home directory *isn't* ```C:/Users/Ale``` it gets displayed in full.

- The third issue is an unintended consequence of the above, plus the fact that busybox-w32 doesn't understand UNC paths. (As evidenced by the other issues you've raised today.) In busybox-w32 root's home directory is ```/```, so the shell unhelpfully 'abbreviates' the leading slash in the UNC path to a ```~```.

Now, root's home directory could be changed but that leads to other problems. And there are further features of Windows privilege elevation that don't fit with the *nix ```su``` model. I'm still thinking about this.

**Comment by ale5000-git** [comment]
For #144 I sugges to patch just `cd`:
- if the current directory start with `//` then give a special handling to `/`
- if the current directory start with `//` and it is the main folder (example: //computer_name/folder_name) then alter `..` to point to `.`

**Comment by ale5000-git** [comment]
Instead of changing the root's home directory what about patching the code to recognize `/` only if th string end or if the following character is NOT `/`?

**Comment by rmyorston** [comment]
We get to choose root's home directory, so we can avoid having to hack the code by making an appropriate choice. On reflection, ```/``` was a poor choice because in Windows it doesn't represent an absolute path. It would have been better to take the hint from ```ShellExecuteEx()``` and use ```C:/Windows/System32```. Not literally that, of course, but whatever ```GetSystemDirectory()``` returns.

Once again, though, Microsoft prove their capacity for doing random unexpected things to spoil your day. On my system ```GetSystemDirectory()``` returns ```C:/Windows/system32```. Spot the difference! It can be fixed by canonicalising the name with ```realpath(3)```.

The other things I was concerned about became less of a problem when I settled on a bolder solution. Initially I tried to limit the use of the root uid to cosmetic changes in the command prompt. I now think it's better to expose the root uid to the whole of busybox-w32 so I've updated ```getuid(2)``` to return a default value by default (duh!) and 0 if the process has elevated privileges. This seems to work nicely. Now when I run ```su``` I get:

```
C:/Users/rmy # cd
~ # pwd
C:/Windows/System32
~ # whoami
root
```

I've also set up a user who isn't an Administrator. When they run ```su``` they're prompted to enter an Administrator's password, so I enter mine.  Mostly things work as expected:

```
C:/Users/blobby # cd
~ # pwd
C:/Windows/System32
~ # whoami
root
```

However, look at the output from ```ls```:

```
~ # cd C:/Users/blobby/
C:/Users/blobby # ls -ld Downloads/
drwxrwxr-x    2 1004     1004          0 Mar 09 08:46 Downloads/
C:/Users/blobby # cd ../rmy
C:/Users/rmy # ls -ld Downloads/
drwxrwxr-x    2 rmy      rmy           0 Mar 09 08:18 Downloads/
```

Although busybox-w32 thinks we're running as root that's just a fiction. We're actually running as **rmy** and the file ownerships reflect that. Indeed, the same is true when **rmy** executes ```su```: there isn't a Windows 'root' user, just normal users with elevated privileges.

However, this is a minor issue. And it doesn't persuade me to make further changes to how file ownership is represented.  On the whole I'm pretty satisfied with how this is shaping up.

There's a new binary, of course, built from current master: [busybox_su7.exe](https://frippery.org/files/busybox/busybox_su7.exe).

**Comment by ale5000-git** [comment]
It work perfectly now.

I'm already satisfied of the current su code. :)
I'm still hoping to get symlink code in some way in the future but I'm closing this for now.

**Comment by ale5000-git** [comment]
@rmyorston: Just one note, `int getuid(void)` when not elevated return DEFAULT_UID which symbolizes the current user, but what happen if the busybox if executed using "Execute as different user" (using shift + right click on busybox_su7 renamed to ash and then "Execute as different user")?

whoami seems to work correctly but is getuid working properly?

**Comment by rmyorston** [comment]
The default uid is hardcoded and always applies to the current user, whoever they may be and however the program was executed. Its actual value doesn't matter, except that it shouldn't match the RID of any user to avoid confusion when displaying file ownership. It isn't really used for very much.

When I'm logged in as **rmy** and "Execute as" **blobby** ```id``` and ```ls``` display the correct details for the logged in user:

```
~ $ id
uid=4095(blobby) gid=4095(blobby) groups=4095(blobby)
~ $ ls -ld Downloads/
drwxrwxr-x    2 blobby   blobby        0 Mar 09 20:26 Downloads/
```

**Comment by rmyorston** [comment]
I've added an implementation of symlink(2). As noted in the discussion above this will only work in certain non-default cases.

The latest [prerelease](https://frippery.org/files/busybox/prerelease) binary has this feature enabled.

Please raise a new issue for any problems.

**Comment by ale5000-git** [comment]
I'm a bit busy in this period but I will surely open a new issue if I notice a problem :)
