### ISSUE TITLE
test -n $a is wrong when $a is zero length

### ISSUE THREAD

**Issue by jack6th** [rmyorston/busybox-w32#146]
a=
test -n $a
echo $?
=> output is 0. It should be 1.
[[ -n $a ]] is also wrong.

**Comment by rmyorston** [comment]
The exit code is correct. Since the variable expands to nothing ```test``` is being called with only one argument, the flag ```-n```. The POSIX specification for [test](https://pubs.opengroup.org/onlinepubs/9699919799/utilities/test.html) says:
>1 argument:
Exit true (0) if $1 is not null; otherwise, exit false.

To get the effect you want you need to quote the expansion of the variable to ensure a second argument is present even if the variable is empty: ```test -n "$a"```

**Comment by rmyorston** [comment]
Which may lead to the question: "So why doesn't ```test``` complain if ```-n``` appears without a second argument?"

It can't do that because the 1 argument case is documented behaviour: ```test "string"``` and ```test -n "string"``` are equivalent.

```test -n``` responds with exit code 0 because it's telling us that the string ```-n``` has non-zero length.

**Comment by ale5000-git** [comment]
@jack6th

To summarize, the correct code to check a var (that can possibly be empty) is this:
```
a=
test -n "$a"
echo $?
```

**Comment by jack6th** [comment]
OK.
The busybox sh is very different from bash.
Where can I find a complete posix shell manual like GNU's bash manual?

**Comment by rmyorston** [comment]
I'm not aware of a manual for BusyBox ash. For the POSIX shell itself there's a [specification](http://pubs.opengroup.org/onlinepubs/9699919799/utilities/V3_chap02.html), but that's not really a manual.

A couple of resources I've found useful and/or interesting are:
- [Insufficiently known POSIX shell features](https://apenwarr.ca/log/?m=201102#28)
- [Rich’s sh (POSIX shell) tricks](http://www.etalabs.net/sh_tricks.html)

Since BusyBox ash is based on dash the [man page](https://linux.die.net/man/1/dash) for that is somewhat relevant.

However, BusyBox ash has diverged from dash and has imported a number of features from bash. It would be great if someone were to produce a full description of BusyBox ash, but I don't think such a thing exists at the moment.
