### ISSUE TITLE
Change title crash

### ISSUE THREAD

**Issue by ale5000-git** [rmyorston/busybox-w32#153]
I was trying to change title but without display anything if the command is not supported but I got a Busybox crash:
`$(echo -en '\033]0;Test title...\007')`

This cause an infinite loop:
`echo -ne "\ekTitle\e\\"`

**Comment by rmyorston** [comment]
Try this, built from current git master: [busybox_esc.exe](https://frippery.org/files/busybox/busybox_esc.exe)

**Comment by ale5000-git** [comment]
Thanks, now the problems are gone but it would be nice to support also these to change title:
`printf '\033]2;Title1\007'`
`echo -ne '\033kTitle2\033\\'`

**Comment by rmyorston** [comment]
> printf '\033]2;Title1\007'

This is due to how ```printf``` outputs text and how busybox-w32 processes escape sequences:
- ```printf``` outputs each character and octal escape individually
- busybox-w32 needs to see the whole of an escape sequence as a single string.

I don't think either of those is going to change so if you need to use ```printf``` you'll have to resort
to workarounds like:
- ```printf '\033]2;Title1\007' | cat```
- ```echo -n $(printf '\033]2;Title1\007')```

> echo -ne '\033kTitle2\033\\'

Why would we need this?
