### ISSUE TITLE
rm -f bug

### ISSUE THREAD

**Issue by ale5000-git** [rmyorston/busybox-w32#155]
`rm -f folder_name/*` fail when the folder is empty.
It is normal for `rm folder_name/*` to fail when the folder is empty but `rm -f folder_name/*` shouldn't fail.

It was working fine in previous versions of busybox but in the latest it no longer work.

**Comment by rmyorston** [comment]
This is due to commit 325fee1f92.

In this case it causes ```stat(2)``` to return the error code ```EINVAL``` which isn't what ```rm -f``` was expecting, so it reports it. Changing the error code to ```ENOENT``` will fix it.

**Comment by rmyorston** [comment]
I think it might be a good idea to make prerelease binaries available on a slightly more formal basis.

The latest prerelease will be available as [busybox_pre.exe](https://frippery.org/files/busybox/prerelease/busybox_pre.exe). Currently this is a copy of [busybox-w32-PRE-3028-g18bffeae4.exe](https://frippery.org/files/busybox/prerelease/busybox-w32-PRE-3028-g18bffeae4.exe) which includes the fix for this issue.

**Comment by ale5000-git** [comment]
It fix the problem, thanks.

Personally I suggest to setup automatic testing on Travis CI
