### ISSUE TITLE
Fix df detection of network folders please

### ISSUE THREAD

**Issue by ale5000-git** [rmyorston/busybox-w32#164]
`df` currently:
```
Filesystem           1K-blocks      Used Available Use% Mounted on
C:                   487591932 480915836   6676096  99% C:/
Z:                   487591932 480915836   6676096  99% Z:/
```

But `Z:/` should report that it is a mount of an UNC path.

**Comment by rmyorston** [comment]
```df``` in the latest prerelease reports the origin of mapped drives.

**Comment by ale5000-git** [comment]
It works perfectly, there is only an alignment issue, I'm not sure if it is supposed to behave like this.

See:
![alignment](https://user-images.githubusercontent.com/15793015/55333686-1aa08380-5498-11e9-9ba5-7541a90f7468.png)

**Comment by rmyorston** [comment]
It is supposed to do that. At least, upstream BusyBox does the same thing.

The idea is that if the filesystem name is too long the entry is split into two lines so that the other columns remain aligned. There's an alternative POSIX-compatible mode (```df -P```) which doesn't split entries but results in columns being misaligned. It's easier for scripts to parse, though.

coreutils ```df``` used to have the same behaviour but was changed in 2011 so it never splits lines. I guess too many scripts were being caught out by the split entries. It might be possible to do the same in BusyBox, though getting it to work might require unacceptable bloat.

**Comment by ale5000-git** [comment]
If it is supposed to be like this it is fine, thanks :)
