### ISSUE TITLE
echo and printf cannot display unicode

### ISSUE THREAD

**Issue by jack6th** [rmyorston/busybox-w32#174]
busybox64 v1.32.0
CJK characters show ?? or squares
eg.
busybox64 echo 字

**Comment by rmyorston** [comment]
As I've remarked before (issue #61), support for character encodings and code pages in Microsoft Windows is a huge mess.  It's not something I feel able to tackle.

**Comment by jack6th** [comment]
Thanks for the prompt reply.

**Comment by sergeevabc** [comment]
@rmyorston, you gave up on Unicode too soon as [miracles are possible][1]. Moreover, sir, it’s crucial.

```console

$ printf "Hello, world! Привет, мир!" | wc -m
26 (true)

$ printf  "Hello, world! Привет, мир!" | awk  "{print length}"
26 (true)

$ file hello.txt
hello.txt: UTF-8 Unicode text, with no line terminators

$ cat hello.txt
Hello, world! �?�?��?��', �?��?! (wtf?!)

$ cat hello.txt | wc -m
35 (false)

$ awk {"print length"} hello.txt
35 (false)

$ awk-gitforwindows "{print length}" hello.txt 
26 (true)
```

Used: [hello.txt](https://github.com/rmyorston/busybox-w32/files/4326319/hello.txt)

[1]: https://github.com/Cyan4973/xxHash/issues/293#

**Comment by sergeevabc** [comment]
cc: @benhoyt
Alas, GoAwk of yours is also susceptible to this Unicode misfortune as it outputs 35 instead of 26.

**Comment by benhoyt** [comment]
@sergeevabc Yeah, the AWK spec is not clear on this point. For GoAWK I chose to go with the original `awk` behavior (number of bytes) rather than `gawk`'s behavior. Counting "character length" is a minefield in Unicode once you start going down this road anyway. For example, here's 1 emoji character, but `gawk` prints 2 (it's 2 unicode runes of 4 bytes each in UTF-8):

```
~/go/src/github.com/benhoyt/goawk$ echo 👶🏻 | gawk '{print length}'
2
~/go/src/github.com/benhoyt/goawk$ echo 👶🏻 | ./goawk '{print length}'
8
```

**Comment by sergeevabc** [comment]
@benhoyt, who cares about emojis within CLI? Leave them to hipsters — there are real life tasks to be simplified, which is what computers are all about in the first place. For example, writers of various kind from diarists and journos to poets and prosaists, who need to measure their output. Should they rely on fancy shareware editors or [online services][1] to count characters instead of a portable offline low-memory-footprint one-liner?  

[1]: https://duckduckgo.com/?q=count+characters

**Comment by sergeevabc** [comment]
@benhoyt, ```gawk`` has two modes to satisfy various (natural and technical) needs, by the way.
```
$ gawk "{print length}" hello.txt
26

$ gawk -b "{print length}" hello.txt
35
```
```-b``` means ```--characters-as-bytes```

**Comment by arnoldrobbins** [comment]
@benhoyt I think POSIX is pretty clear that `awk` works in terms of characters and not bytes.  For Goawk, it shouldn't be hard to manage as Go has built-in UTF-8 and Unicode support. Contact me directly if I can help.

W.R.T. gawk and emoji's, what else can gawk do if gets two separate Unicode code points? (Copying / pasting into mate-terminal shows it as two characters, a baby face and a square block. Weird.)

**Comment by benhoyt** [comment]
@arnoldrobbins True, you're right -- I had remembered wrong. The [POSIX spec](https://pubs.opengroup.org/onlinepubs/9699919799/utilities/awk.html) says "The index, length, match, and substr functions should not be confused with similar functions in the ISO C standard; the awk versions deal with characters, while the ISO C standard deals with bytes."

I've opened https://github.com/benhoyt/goawk/issues/35 to discuss further over on the GoAWK repo -- would love any recommendations you have there, @arnoldrobbins!
