### ISSUE TITLE
No output when using alias | sort | grep -n . 

### ISSUE THREAD

**Issue by Klexer** [rmyorston/busybox-w32#176]
When I try to sort or filter my list of aliases using pipe '|', there is no output.
```
~ $ alias | sort
~ $ alias | grep -n .
~ $
```
Otherwise I get a result in the upstream busybox from ubuntu or MSYS2.

P.S. The redirection of the output with '>' works fine.

**Comment by rmyorston** [comment]
The issue here is that the alias table wasn't being copied when the shell was forked. The original author of the busybox-w32 port never got around to implementing that and nobody has noticed until now.

I've added the necessary code. There's a prerelease binary in [this directory](https://frippery.org/files/busybox/prerelease) if anyone would like to try it.

**Comment by rmyorston** [comment]
I noticed there was a similar problem with the ```history``` shell builtin. This has also been fixed and a new prerelease binary uploaded.

**Comment by Klexer** [comment]
Thanks.
