### ISSUE TITLE
Is it possible to compile httpd to busybox-w32 by myself?

### ISSUE THREAD

**Issue by HuangShumin** [rmyorston/busybox-w32#179]
I don't know if httpd is possible to complile to Windows busybox. Thank you for answer.

**Comment by rmyorston** [comment]
It isn't currently possible to build the ```httpd``` applet in busybox-w32.

The server uses some Unix features, like the ```fork(2)``` system call and certain signals, that aren't available on Windows.

**Comment by HuangShumin** [comment]
Appreciate your reply:)

**Comment by rmyorston** [comment]
Reopening this because I've worked around the missing Unix features. ```fork(2)``` has been replaced with appropriate use of ```spawn``` functions.  ```SIGALRM``` has been replaced with a timeout on ```poll(2)```. ```SIGHUP``` isn't supported so it isn't possible to force the server to reread its configuration file.

Some of the optional features of ```httpd``` have been enabled but not support for CGI.

Check the source code in ```networking/httpd.c``` for documentation of the configuration file.

There's a new pre-release binary [on my website](https://frippery.org/files/busybox/prerelease).

**Comment by HuangShumin** [comment]
I'm downloading for testing. If any issue found, I will post it here in order to improve win32 httpd:)

**Comment by HuangShumin** [comment]
I copy busybox-w64-FRP-3329-gcf0fa4d13.exe to C:\Windows\System32 and rename it as sh.exe
Then I download busybox-w32-PRE-3441-g9181e1363.exe to a local directory as busybox-test.exe which has a sub-directory www.

I found that httpd cannot find www if I run with `./busybox-test.exe httpd -fvvvp 8080 -h www'

httpd: can't change directory to 'www': No such file or directory
httpd: can't change directory to 'www': No such file or directory
httpd: can't change directory to 'www': No such file or directory

I confirm there's a www direcory with same to busybox-test.exe

**Comment by rmyorston** [comment]
The issue with changing directory should be fixed by commit 1e97d7904.

The same problem affects upstream BusyBox when built in NOMMU mode. I'll submit a patch.

There's a new pre-release binary with this fix.

**Comment by rmyorston** [comment]
I spotted another issue. The server prevents access to local ```httpd.conf``` files and URLs requiring authentication. Since Windows filesystems are usually case-insensitive a client can circumvent this security by using a URL with a different case, e.g.```Httpd.conf```.

Prevent this by using case-insensitive comparisons.

The latest pre-release binary has this fix.
