### ISSUE TITLE
`rm` doesn't seem to understand globs

### ISSUE THREAD

**Issue by fluffynuts** [rmyorston/busybox-w32#187]
I installed `busybox` via `scoop` and it clobbered my `gow`. I really just wanted `sha256sum`, but didn't bother about trying to reset my scoop shims until I noticed that `rm` doesn't seem to understand glob patterns, eg `rm foo*` returns an error: "No such file or directory", even when there are, eg, "foo.bar", "foobar.txt" in the current folder

from `scoop info busybox`, I get the version: 3445-g10e14d5eb

**Comment by rmyorston** [comment]
If you're running ```rm``` from Windows ```cmd.exe``` that's the expected behaviour of the default build. There's an explanation [on my website](https://frippery.org/busybox/globbing.html). The tl;dr is that the default build is configured for use from the BusyBox shell.

A non-default build with Windows-style globbing is also available: [busybox_glob.exe](https://frippery.org/files/busybox/busybox_glob.exe).

**Comment by fluffynuts** [comment]
hm, then I suppose I should talk to the maintainer for the scoop bucket as the shim is made available on a global scale for the current user, irrespective of shell, meaning that the shimmed `rm.exe` installed by installing `busybox` definitely does not do what the user expects.

**Comment by rmyorston** [comment]
See commit f416974.

**Comment by HuangShumin** [comment]
`#include <stdio.h>
#include <limits.h>

int main(int argc, char *argv)
{

	FILE *fp;
	int status;
	char path[PATH_MAX];


	fp = popen("ls *", "r");
	if (fp == NULL)
		/* Handle error */;


	while (fgets(path, PATH_MAX, fp) != NULL)
		printf("%s", path);


	status = pclose(fp);
	if (status == -1) {
		/* Error reported by pclose() */
	} else {
		/* Use macros described under wait() to inspect `status' in order
		   to determine success/failure of command executed by popen() */
	}
}`

compiling such code cannot execute in busybox shell.

any solution?

**Comment by rmyorston** [comment]
Background:

- Commit f416974 has details of how globbing is now controlled in busybox-w32.
- ```popen(3)``` on Unix uses the shell to run its command, so wildcards are expanded; ```_popen()``` in the Microsoft C runtime uses ```cmd.exe``` to run its command, so the command being invoked is responsible for expanding wildcards.

When the sample program is run from a BusyBox shell globbing is turned off because the shell sets the environment variable ```BB_GLOBBING=0```. The wildcard argument to the command run by ```popen()``` is therefore not expanded.

The MSYS2 shell knows nothing about ```BB_GLOBBING``` so it isn't set when the sample program is run. If the command is a BusyBox binary it will therefore expand any wildcard arguments.

A workaround is to unset the environment variable before calling ```popen()```:
```
    putenv("BB_GLOBBING=");
```

**Comment by HuangShumin** [comment]
thank you sincerely, finally understand the globbing mechnism of busybox-w32, cool design!
