### ISSUE TITLE
awk string concatenation is  very slow

### ISSUE THREAD

**Issue by jack6th** [rmyorston/busybox-w32#193]
busybox v1.33.0-FRP-3532-g01a256149 on Windows 10 64bit 1903   
```
$ busybox time awk "BEGIN{while(++i<30000) s=s i}"
real    0m 18.83s
user    0m 18.78s
sys     0m 0.06s
```
While on Linux the same command takes 0 second.

**Comment by rmyorston** [comment]
Careful, now. BusyBox on Linux is likely to be configured differently from busybox-w32. On Linux the command
```
busybox time awk "BEGIN{while(++i<30000) s=s i}"
```
will probably use BusyBox ```time``` to time the system's ```awk``` (which is probably ```gawk```).

Here are my timings:
- GNU awk: 0.015s
- Fedora 31 BusyBox: 1.8s
- Default build of BusyBox on Fedora 31: 3.5s
- busybox-w32 on Windows 10: 11.8s

Clearly all variants of BusyBox awk are much, much slower than gawk. The BusyBox supplied with F31 is a static build which is twice as fast as a hand-built binary with the default configuration.

busybox-w32 is more than three times slower than a native Linux build on the same (virtual) hardware. That's not a terribly good result. I'll look into it.

**Comment by jack6th** [comment]
You are right.   On Linux I should use the command below.   
```
time busybox awk "BEGIN{while(++i<30000) s=s i}"
```
It takes 2.6 seconds.

**Comment by rmyorston** [comment]
Profiling the test case on Linux shows that 77% of the time is spent in ```xasprintf()``` (line 3030 of editors/awk.c in the current version) and 22% in ```xstrdup()``` (line 962). The first implements string concatenation and the second variable assignment.

The call to ```xasprintf()``` can be replaced with code like this:
```
            buf = xmalloc(strlen(L.s) + strlen(sep) + strlen(R.s) + 1);
            strcpy(buf, L.s);
            if (*sep != '\0')
                strcat(buf, sep);
            strcat(buf, R.s);
```
The call to ```xstrdup()``` is unnecessary in this case. In earlier releases of BusyBox there was code to optimise it away but it was commented out (line 2770) to fix a bug. It can be reinstated and fixed with code like this:
```
            if (R.v == v1+1 && R.v->string && !(R.v->type & VF_NUMBER)) {
                res = setvar_p(L.v, R.v->string);
                R.v->string = NULL;
            } else {
                res = copyvar(L.v, R.v);
            }
```
With these changes the test case runs in 0.58s on Linux and 0.65s on Windows 10: six times and eighteen times faster.

However, I hesitate to make these changes because there are costs:
- It increases the size of the binary by 144 bytes.
- The upstream BusyBox maintainer prefers reducing size over performance (as evidenced by the bug fix at line 2770) and is unlikely to accept these changes without good reason. I'm unwilling to carry patches that aren't upstream unless absolutely necessary.

The test case creates a very long string by repeated concatenation. Is this a common use case? Most of the string concatenations in the book 'The AWK Programming Language' are quite short and would benefit little from these changes.

**Comment by jack6th** [comment]
Thanks for finding the bug.   
I think I can use mawk instead of busybox awk on windows for better performance.

**Comment by rmyorston** [comment]
As another data point here's a different test:
```
time busybox awk "BEGIN{while(++i<1000000) \"abc\" i}"
```
It measures a small string concatenation without an assignment.  On Fedora 31 the ```xasprintf()``` optimisation reduces the time from 0.58s to 0.45s; on Windows 10 the time goes down from 0.84s to 0.62s. gawk on Fedora 31 takes 0.23s.

**Comment by jack6th** [comment]
So the speed of small string concatenation without an assignment is acceptable.   
User should avoid very long string concatenation.  Specially on windows.
