### ISSUE TITLE
Make every access to /bin/* search for the executable in PATH

### ISSUE THREAD

**Issue by longnguyen2004** [rmyorston/busybox-w32#195]
Most autotools configure script hardcoded the shell to be `/bin/sh`, resulting in the script not finding the shell to use. If there's an access to `/bin/*`, it should first check if the program to execute is an applet, if not then it should search in the PATH. That way most scripts can be run as-is without any modifications.

**Comment by rmyorston** [comment]
Not directly related to the issue at hand but Unix-style paths starting with a slash are treated as relative to the current drive in Windows. If a shell is installed in ```C:/bin/sh.exe``` it can be run as ```/bin/sh``` if one is on the ```C:``` drive but not any other.

I've extended the work that was done for issue #158 so the busybox-w32 shell treats executables with paths starting with a slash as being on the system drive (usually ```C:```).

However, the issue here is how to handle hard-coded Unix-style paths to binaries without having to install them. The latest commit has special treatment for paths starting with ```/bin```, ```/usr/bin```, ```/sbin``` or ```/usr/sbin```. If the referenced binary can't be found but the program is a built-in applet, the applet is run. I haven't implemented searching PATH.

There's a new pre-release binary [on my website](https://frippery.org/files/busybox/prerelease) with these changes.

**Comment by longnguyen2004** [comment]
Thanks for the change. Autoconf scripts now work without any modifications.

**Comment by ale5000-git** [comment]
@rmyorston
Personally I don't like placing things directly on C:\
Isn't possible to control it with an environment variable?

Example:
`export BASE_PATH_FOR_LINUX_STYLE_PATH=C:/ProgramData`

then:

> /bin/sh => C:/ProgramData/bin/sh

**Comment by rmyorston** [comment]
I don't recommend installing links and as a result of this issue it isn't necessary to do so to get paths like ```/bin/sh``` to work. So I don't see much use for making the location of such paths configurable.

Still, commit a20dad672 adds minimal support for a ```BB_SYSTEMROOT``` environment variable.

- ```BB_SYSTEMROOT``` should probably only refer to a Windows-style absolute path, but this isn't checked.
- Set ```BB_SYSTEMROOT``` using the Windows Control Panel or ```setx```, not as a shell variable: the shell itself won't see the environment variable.

There's a pre-release binary in [the usual place](https://frippery.org/files/busybox/prerelease).

**Comment by ale5000-git** [comment]
Your changes can be useful but defeat my main point: do not touch the system.
With `portable` I mean that can be run on any system and leave no trace on the system itself so I can for example copy busybox.exe and the shell sctipt on a pen drive and just run it on any system.

One example of use could be have a .bat files that redirect linux path of dpkg to a folder in the pen drive and the run the ash shell from the .bat file.

While on my system I usually copy busybox to the system folder to use it directly, on other systems it could be usefull to don't modify the system and have files like `.ash_history` and all files that read/write on linux pathes near the busybox.exe
