### ISSUE TITLE
BusyBox-1.33: ansi colors partially supported

### ISSUE THREAD

**Issue by edgarm1964** [rmyorston/busybox-w32#201]
LS, I'm using busybox 1.28 on windows and in this version I can use the following as a prompt in ash:

PS1='\[\e[48;5;128m\e[38;5;231;1m\]ENV\[\e[0m\] ${PWD##*[!/]+(/)}$ '

Oh, "\e" is escape. This shows 'ENV' in bright white, bold and with a certain background colour.

In busybox 1.33, I get:

⃖[48;5;128m ⃖[38;5;231;ENV C:/temp$

The left arrow is the escape character.

But, the limited ansi colours (foreground: \e[30m..\e[37m, background: \e[40m..\e[47m) appear to work.

Is there some option I have to set? Unset?

Kind regards, Edgar Matzinger.

**Comment by avih** [comment]
Are you saying that this `\e[48;5;128m\e[38;5;231;1m` worked in busybox-w32 1.28 but doesn't work in 1.33?

In general, it does ansi emulations for widnows console, which traditionally supports only 8x2 colors (the normal 8 colors and their bright versions), so it just can't display 256 colors, and I don't think busybox ansi emulation ever translated 256 colors (which is what 38/48; 5 is)  to 8/16 colors.

However, with windows 10 the terminal now supports many native features, including full colors escape sequences (8/16/256/true), so on windows 10 you can enable it by disabling the busybox emulation, and activating the windows 10 VT mode.

You can do that from within the shell with `export BB_SKIP_ANSI_EMULATION=2`, or from cmd.exe before running busybox with `set BB_SKIP_ANSI_EMULATION=2`.

**Comment by rmyorston** [comment]
I'm not clear which versions of BusyBox you're using, so I'll talk generally about the problem and hope it addresses your issue.

By default busybox-w32 uses the Windows console API to emulate ANSI escape sequences. The API only supports a limited range of colours.

Setting the environment variable ```BB_SKIP_ANSI_EMULATION=2``` makes busybox-w32 try to detect if your terminal program has native support for ANSI escape sequences. If it does the emulation is skipped and the escape sequences are output directly. Depending on the terminal this may allow you to use additional colours.

Note that setting the variable in the shell you're currently using won't have the desired effect because the emulation will already have been enabled: it has to be set before the shell starts.

This feature was introduced in version FRP-3466-g53c09d0e1: [release notes](https://frippery.org/busybox/release-notes/FRP-3466.html).

**Comment by edgarm1964** [comment]
> Are you saying that this \e[48;5;128m\e[38;5;231;1m worked in busybox-w32 1.28 but doesn't work in 1.33?

Yes, I am.

And I'm sorry to have forgotten to mention that I'm running on Windows 2012R2...

**Comment by avih** [comment]
> Yes, I am.

Can you please post the official download links which you used for these two versions (one where it works and one where it doesn't)?

**Comment by edgarm1964** [comment]
I've downloaded both versions from https://frippery.org/busybox/

I have to say the 1.28 version was a few years ago...

**Comment by rmyorston** [comment]
It was only by chance that earlier releases did something sensible with your example code. Commit 8da63be14 tightened up the detection of invalid escape sequences. The last release that "worked" was FRP-3025-gc01300361.

FRP-1601-gc87d9b4b2 is now more than three years old so is no longer available on my website.

**Comment by avih** [comment]
Well, the oldest at that link is busybox-w32-FRP-1668-g236e13e3d, and it doesn't display display PS1 correctly when I set it like so: `PS1='[\e[48;5;128m\e[38;5;231;1m]ENV[\e[0m] ${PWD##*[!/]+(/)}$ '` (copied from your first post), in the following ways:
1. It doesn't strip the outer square brackets (which are used to denote that the content between them is not printable for line-width calculations during editing). I think you copied your line incorrectly, because usually these square brackets should be preceded with `\`, like so: `PS1='\[\e[48;5;128m\e[38;5;231;1m\]ENV\[\e[0m\] ${PWD##*[!/]+(/)}$ '`
2. The color is white on gray - like in your screenshot, but it should be white on magenta-ish when displayed correctly.

That being said, it does seem to behave differently on busybox-w32 1.33. Latest versions do print the escape sequence literally - visibly. I'm not sure why, but either way it never worked correctly, it just works in a different incorrect way now.

On anything earlier than windows 10 you should stick to the normal 8 colors 30-37, 40-47, possibly with bold etc

**Comment by edgarm1964** [comment]
> PS1='\\[\\e[48;5;128m\\e[38;5;231;1m\\]ENV\\[\\e[0m\\] ${PWD##*[!/]+(/)}$ '

Yes, I have this. Didn't notice the \\ disappeared. OK, will stay with the "normal 8 colors." Or drop CMD completely.

Thanks!

**Comment by rmyorston** [comment]
Release FRP-3902-g61e53aa93 adds emulation of the escape sequences mentioned above. @avih's ```sgrtab``` and ```shlolcat``` now work, even in ancient Windows consoles.

**Comment by avih** [comment]
> ... sgrtab and shlolcat now work, even in ancient Windows consoles.

Very nice, this was indeed an annoying limitation (didn't try it out yet), and I see you also got a shiny new screenshot at the homepage :)

How did you even find `shlolcat`? I don't think I advertised it anywhere... (for reference, https://github.com/avih/sgrtab and https://github.com/avih/shlolcat )

**Comment by rmyorston** [comment]
>I see you also got a shiny new screenshot at the homepage :)

This is the first time I've used Windows 10 in the screenshot. Had to get the full range of colours.

>How did you even find shlolcat?

By snooping about among your repositories, of course! I already knew about ```sgrtab``` and thought there might be some other good stuff there too.

**Comment by avih** [comment]
Right. It's cute and fast. Needs pipefail though to return an error code on invalid FILE (or if `od` is not found etc). Also, it assumes UTF8 currently so it doesn't progress the color for bytes which don't look like UTF8 leading/single byte (e.g. upper values with a codepage-based single-byte encodings).

> sgrtab and shlolcat now work

By the way, I tried shlolcat with BB_SKIP_ANSI_EMULATION=0 and noticed some glitches (even with `-c8` to output only 8 colors). IIRC mainly that there's occasional bold-black output (which shlolcat shouldn't print) . No minimal test case yet, and I don't yet know if it's an emulation or shlolcat issue, but I hope to know more soon.

**Comment by avih** [comment]
> ... with BB_SKIP_ANSI_EMULATION=0 and noticed some glitches (even with -c8 to output only 8 colors). IIRC mainly that there's occasional bold-black output ...

So, few things:

It seems to be OK with -c8. I think I encountered some issue when setting BB_SKIP_ANSI_EMULATION=0 from the sh prompt. It's not worth chasing (unless you want to), but it seems OK if I set it at `cmd.exe` prompt before running `busybox sh`.

I now also see the elaborate `process_24bit()` and `process_8bit()`, which indeed can map to bright black, and indeed the ones which I noticed could be considered correct.

FWIW, personally I think the conversion is too elaborate for its own sake, because you rely on the terminal colors being the default (which definitely might not be the case) to apply a sophisticated LAB color conversion, and because the quantization is so extreme (from 256 or 16M colors to 16) that IMHO all the accuracy simply becomes effectively meaningless due to the low output color resolution. Also, I think there could be issues if the bg color ends up needing bright while the fg doesn't (and vice verse), because IIRC console colors have one bit for the whole cell brightness.

I think that a trivial linear conversion would be equally useful and not noticeably different, and I'd even make it to 8 and not 16 colors, but you're the maintainer, so that's up to you.

However, I think I also encountered a bug at the parsing code when a true color escape is followed by a `;`. In the following code `X` is printed in ANSI red, 256 colors (bold) red, and true colors (bold) red:
```sh
printf "\033[31mX\033[m\n"
printf "\033[38;5;196mX\033[m\n"
printf "\033[38;2;255;0;0mX\033[m\n"
```

But if you replace `X` with `;` then the first two lines print `;` correctly in red, while the last line prints `;` in white.

**Comment by avih** [comment]
> shlolcat ... Needs pipefail ...

Fixed in master.

**Comment by rmyorston** [comment]
The issue with semicolons should be fixed. Try the latest prerelease binary on my [website](https://frippery.org/files/busybox/prerelease/).

>FWIW, personally I think the conversion is too elaborate

Maybe so, but it does look prettier, I think. Anyway it's only 560 additional bytes, which is as nothing compared to the 30K of bloat added by ```bc``` in the last release.

The code still includes my original, less elaborate conversion which can be enabled at build time if required.

**Comment by avih** [comment]
> The issue with semicolons should be fixed

Confirmed fixed in `busybox-w32-PRE-3904-gdfa16f84d.exe`. Thanks.

Off topic, I always spend way too much time to find the link to the directory listing at the site. Any chance you could move/put "Download latest: ..." and "See all builds" near the top in bold?

> ... but it does look prettier

I know that feeling :) I'd still use the simpler version just to throw away code, but I still get it :)
