### ISSUE TITLE
Document path nomenclature

### ISSUE THREAD

**Issue by vpaesa** [rmyorston/busybox-w32#205]
Hello,
I found this comment below in ash.c very helpful to understand how to reach files in the Windows filesystem.
For the benefit of others, may you please consider adding that text to your top README.md file?
```
/*
 * There are five cases that make some kind of sense
 *
 * Absolute paths:
 *    c:/path
 *    //host/share
 *
 * Relative to current working directory of other drive:
 *    c:path
 *
 * Relative to current root (drive/share):
 *    /path
 *
 * Relative to current working directory of current root (drive/share):
 *    path
 */
```
Thanks in advance

**Comment by rmyorston** [comment]
Yes, I really should pull together the information about Windows paths that's scattered through the release notes, GitHub issues and code. I'll look into it.

**Comment by avih** [comment]
These 5 kinds of paths are exactly what works on windows everywhere else too. The formal specifications require backslashes, but most windows APIs support forward slashes as well (e.g. `fopen`). So far, busybox-w32 is identical to anything else on windows.

What would make a difference, however, would be supporting some global root path starting with `/`, either always, or possibly similar to cygwin's `/cygdrive/c/whatever`, because many scripts expect any path starting with `/` to be absolute - but in busybox-w32 that's not the case - as mentioned at the original post.

**Comment by rmyorston** [comment]
I've updated the README. Still working on a more detailed document.

**Comment by rmyorston** [comment]
I've written some more words about pathnames [here](https://frippery.org/busybox/paths.html).

Before I make a fool of myself by publishing it to the world I'd appreciate it if you could check for typos, errors, blatant falsehoods and things in need of clarification. Thanks.

**Comment by vpaesa** [comment]
Other than one typo ("th**e**n it was before.", might be "th**a**n it was before."), your https://frippery.org/busybox/paths.html looks to me a nice, vivid, and truthful description of paths.
Thanks, sir!

**Comment by rmyorston** [comment]
@vpaesa Thanks for proofreading.

I've fixed the typo and rewritten the section on ```/path/to/file``` to make it clear busybox-w32 only applies special treatment in certain cases.

The page is now linked from my website and README.md.
