### ISSUE TITLE
Add curl applet

### ISSUE THREAD

**Issue by shpati** [rmyorston/busybox-w32#214]
Hi. Thank you so much for the Windows native port of BusyBox, and thank you also for providing the binaries for download. 
I would kindly ask you to add the curl applet to BusyBox. I find curl to be a very useful command and I assume there are many other users that would like to see it included in BusyBox.  

Can it be done?

**Comment by rmyorston** [comment]
BusyBox (and busybox-w32) has wget. Are there any specific features of curl that you need?

**Comment by shpati** [comment]
curl supports a much larger range of protocols than wget, making it a more general-purpose tool. A comprehensive comparison btw. curl, wget and other similar tools can be found in the table linked here: [https://curl.se/docs/comparison-table.html](https://curl.se/docs/comparison-table.html)
The ability to upload and use many more protocols makes curl a nice tool to have in busybox imho. wget on the other hand has recursion, which curl does not, so I can appreciate wget's usefulness. I use both these commands, depending on the specific need.

**Comment by garoto** [comment]
Is there a `curl` applet in busybox? I can't find it.

**Comment by yetanothergeek** [comment]
Some of curl's extra protocols (like pop3, tftp, and telnet) are already supported by other busybox applets. Others (like dict and gopher) are not so commonly used these days. Still others (like krb, ssh, and http2) depend on third-party libraries, something that busybox tries to avoid.

**Comment by shpati** [comment]
I very much like the fact that busybox is small (under 1MB), lean (single executable) and a tradeoff has to be made at some point in terms of what can be included and what not. How about adding the curl (or any other) executable to the same folder as busybox, and calling/executing it through busybox, can I do that? Some sort of exec command I mean. I don't seem find any way to do it.

**Comment by garoto** [comment]
`busybox64.exe sh -c c:\\bin\\curl.exe`

**Comment by avih** [comment]
The point is that busybox-w32 is an adaptation of upstream busybox to win32. Upstream busybox doesn't have curl, and so busybox-w32 doesn't have it either. Adding "nice to have" programs or applets to busybox-w32 is outside the scope of this project.

There are plenty of useful tools to have on win32 also other than curl, and you can collect all them into some directory and simply add this directory to your PATH so that they can be found (either from windows command prompt or busybox-w32 shell) without specifying full path.

If you want them to be found (without specifying full path) only in busybox-w32 shell but not from the windows command prompt, then you can add this utilities directory to your path during the busybox-w32 shell init.

**Comment by shpati** [comment]
> `busybox64.exe sh -c c:\\bin\\curl.exe`

Many thanks @garoto !

@avih I will look into shell init as you suggested, thank you.
