### ISSUE TITLE
Report correct number of links for folders

### ISSUE THREAD

**Issue by ale5000-git** [rmyorston/busybox-w32#254]
`stat folder_name` always return `Links: 2` but it isn't correct.
Junctions behave mostly like hard links, since all junctions of the same folder have the same inode number.

BusyBox can already show all junctions of a folder by using `find . -samefile folder_name` but stat doesn't correctly report the number.

To make it simply I think it is easier to just use: `hdata.nNumberOfLinks + 1`
(to make more correct you would also need to count subfolders but I don't think it is really needed)

PS: Additionally creating a junction of a folder inside it cause infinite loop of `ls -R` until `Too many levels of symbolic links`.

**Comment by rmyorston** [comment]
On Unix the link count of a directory with no subdirectories is two because the directory name itself is one and the ```.``` inside is a second. Every time you add a subdirectory the ```..``` in the subdirectory adds another link to the parent's count. The link count is kept in the directories' inode so it can be fetched by ```stat(2)``` at relatively little cost.

Windows doesn't look at things the same way. The filesystem always reports a link count of one for directories. Counting the number of links by searching the entire filesystem for matching inode numbers is likely to be prohibitively expensive. There's also the ```FindFirstFileNameW/FindNextFileNameW``` API which can find all hard links to a given file but it doesn't work for directories.

>creating a junction of a folder inside it

I'm not clear what this means. Can you give an example?

**Comment by rmyorston** [comment]
>But have you tried to use hdata.nNumberOfLinks from here after creating a junction?

Yes, I checked that: the link count is still one.

**Comment by ale5000-git** [comment]
Well, then I guess there isn't any fast way to get the count.

Is it possible to improve `ls` to list them?
ls -la on bash for Windows:
```
drwxr-xr-x 1 User None 0 May 11 15:10 .
drwxr-xr-x 1 User None 0 May 11 14:46 ..
lrwxrwxrwx 1 User None 9 May 11 14:46 b -> /c/TEST/a
```

ls -la on busybox for Windows:
```
drwxrwxr-x    2 User     User             0 May 11 15:10 .
drwxrwxr-x    2 User     User             0 May 11 14:46 ..
drwxrwxr-x    2 User     User             0 May 11 14:46 b
```

**Comment by rmyorston** [comment]
OK, creating a junction that somehow refers to itself can cause an infinite loop. What point are you trying to make?

**Comment by ale5000-git** [comment]
Is it correct like this? If yes, then nevermind.

About reporting junction in `ls`, is it possible?

**Comment by rmyorston** [comment]
>Is it correct like this? If yes, then nevermind.

I think it's correct.

>About reporting junctions in ls -la, is it possible?

It's pretty straightforward to have junctions reported as if they were symbolic links (as bash does in your example above). It gets a bit more complex if you want to be able to distinguish between junctions and symbolic links. Unix doesn't have anything like junctions so the existing BusyBox code has no way to handle them as a separate type of file.

**Comment by rmyorston** [comment]
>I don't know the code enough to be sure but isn't possible to set a custom flag in buf->st_attr or buf->st_mode?

Yeah, something like that. When I was experimenting with this I added a new structure member to avoid stepping on ```st_attr``` or ```st_mode```. But that's just an implementation detail, there lots of other considerations I haven't fully explored yet.

**Comment by rmyorston** [comment]
We've wandered off the original topic, but never mind, let's press on.

busybox-w32 currently resolves directory junctions to their target, so they look like directories. They aren't really, though, which results in odd behaviour.

Set up a directory containing a subdirectory and a junction:
```
~ $ mkdir -p a/dir
~ $ touch a/dir/file
~ $ cmd /c mklink /j a\\link a\\dir
Junction created for a\link <<===>> a\dir
~ $
~ $ ls -l a
total 0
drwxrwxr-x    2 rmy      rmy              0 May 14 10:04 dir
drwxrwxr-x    2 rmy      rmy              0 May 14 10:04 link
~ $
~ $ tar cf - a | tar tvf -
drwxrwxr-x 4095/4095         0 2022-05-14 10:41:11 a/
drwxrwxr-x 4095/4095         0 2022-05-14 10:41:01 a/dir/
-rw-rw-r-- 4095/4095         0 2022-05-14 10:41:01 a/dir/file
drwxrwxr-x 4095/4095         0 2022-05-14 10:41:11 a/link/
-rw-rw-r-- 4095/4095         0 2022-05-14 10:41:01 a/link/file
~ $
```
```link``` looks like a directory and its contents are stored in the tar file.

- ```rm -rf a``` fails to delete directory ```a``` because (YMMV) ```dir``` is deleted first leaving ```link``` without its target, so ```rm``` refuses to delete it.
- ```rmdir a/link``` works, even though ```link``` appears to be a non-empty directory.
- ```rm -rf a/link``` deletes ```link```, as expected, but it also deletes the contents of ```dir```, leaving it empty.

Directory junctions are actually very much like symbolic links, so that's how the latest [prerelease](https://frippery.org/files/busybox/prerelease) treats them.  With the same set up as above:
```
~ $ ls -l a
total 0
drwxrwxr-x    2 rmy      rmy              0 May 14 10:41 dir
lrwxrwxrwx    1 rmy      rmy             18 May 14 10:41 link -> C:/Users/rmy/a/dir
~ $
~ $ tar cf - a | tar tvf -
drwxrwxr-x 4095/4095         0 2022-05-14 10:41:11 a/
drwxrwxr-x 4095/4095         0 2022-05-14 10:41:01 a/dir/
-rw-rw-r-- 4095/4095         0 2022-05-14 10:41:01 a/dir/file
lrwxrwxrwx 4095/4095         0 2022-05-14 10:41:11 a/link -> C:/Users/rmy/a/dir
~ $
```
And:
- ```rm -rf a``` works as expected, deleting everything.
- ```rmdir a/link``` fails because ```a/link``` isn't a directory. ```rm a/link``` works.
- ```rm -rf a/link``` only deletes ```link```, leaving ```dir``` intact.

**Comment by rmyorston** [comment]
Back on-topic: junctions aren't really like hard links so there's no need to scan the entire filesystem to find links to directories. Instead it's only necessary to count the number of subdirectories a directory has to get a Unix-style link count.

This has been implemented in the latest [prerelease](https://frippery.org/files/busybox/prerelease). As before, this feature is controlled by a build-time configuration setting, so if it turns out to slow things down too much it can be disabled.

**Comment by ale5000-git** [comment]
It seems to be working perfectly, I don't notice any slowdown.
Thanks.
