### ISSUE TITLE
Backward compatibility for timeout

### ISSUE THREAD

**Issue by ale5000-git** [rmyorston/busybox-w32#258]
Live BusyBox online:
Usage: timeout [-t SECS] [-s SIG] PROG ARGS
Latest BusyBox-w32:
Usage: timeout [-s SIG] [-k KILL_SECS] SECS PROG ARGS

So probably it changed over time.
Is it possible to support -t for backward compatibility (and in this case ignore SECS outside -t)?

**Comment by rmyorston** [comment]
>So probably it changed over time.

It did, with upstream commit c9720a761e88e83265b4d75808533cdfbc66075b (timeout: fix arguments to match coreutils). Live BusyBox is very old.

Since the change was to match coreutils and since upstream didn't include backwards compatibility at the time I guess there's little chance they'd want to add it now.

**Comment by ale5000-git** [comment]
Ok thanks,
