### ISSUE TITLE
Default build with ENABLE_FEATURE_HTTPD_CGI?

### ISSUE THREAD

**Issue by xparq** [rmyorston/busybox-w32#266]
Having a HTTP server (also with auth) is already insane... But I got carried away and tried (everything with a downloaded .exe) to get it doing CGI too, however, it seems to not have it built in.

Is that the case? If so, is it just a matter of adding the flag? (If yes, supporting CGI by default would be such a high-profit feature, opening a portal to the whole new universe of dynamic web..., immensely increasing the usefulness of the `httpd` applet, which may have limited utility as-is beyond being a fascinating toy.)

Is it just the exe size (or would it have some non-trivial implications)? How much if yes? (Also, in case it might help: probably everyone on Windows would happily sacrifice `dpkg*` and `rpm*` etc. to compensate.) Thanks!

**Comment by rmyorston** [comment]
It's not just about size: the CGI feature uses the ```vfork(2)``` system call. This isn't straightforward to implement in Windows so some sort of workaround is necessary.

Since there have been two requests for CGI support recently I'll take a look at the problem. It isn't a priority for me, though, so may take a while. Let's leave this issue open for now.

**Comment by xparq** [comment]
I'm just gluing this nice discussion here for reference: [The beauty of CGI and simple design](https://news.ycombinator.com/item?id=34286622)

**Comment by HuangShumin** [comment]
vfork can be emulated on top of CreateProcess() syscall, by creating a new process running the busybox httpd, and copies all writable pages (data sections, heap, stack, etc.) before resuming the cgi process.

**Comment by HuangShumin** [comment]
Awesome, let's try it.

**Comment by xparq** [comment]
Wow, just noticed this change from last Xmas! :-o

Tried a smoke test just now, works beautifully! Thanks a lot for this absolute gem, Ron!

**Comment by rmyorston** [comment]
Anything that requires a subprocess will cause a console window to appear. This includes external commands, pipes, command substitution, process substitution or subshells.

Anything internal to the shell, such as built-ins like `echo` or `printf`, loops, `if` statements, functions, etc. doesn't need a subprocess and won't cause a console window to appear.

If you intend to use anything that needs subprocesses you can put it in a subshell with `set -o noconsole`. This will result in a single console window being created even if there are many subprocesses.
```sh
#!/bin/sh

echo "Content-type: text/html"
echo
echo "Hello world"

(
	set -o noconsole
	echo "<br>Hello pipe" | grep H
)
```
Without the subshell two console windows would appear, one for each subprocess in the pipe. With the subshell and `set -o noconsole` a single console window is created and will be hidden as soon as possible.

**Comment by xparq** [comment]
> Anything internal to the shell, such as built-ins like echo or printf, loops, if statements, functions, etc. doesn't need a subprocess and won't cause a console window to appear.

Yes, that's how I interpreted it.

So, if we are on the same page, there exists a case, where there isn't a terminal window (i.e. no subshells etc.), and that should be something like this:

cgi-bin/test.sh:

    #!/bin/sh
    echo "Content-type: text/html"
    echo
    echo "Wow, Hello there!"

Then:

    busybox-w64u-PRE-5288-ge960b0d69.exe httpd
    
And:

    http://localhost/cgi-bin/test.sh
    
But there is a terminal popup (disappearing immediately).
Adding `set -o noconsole` makes no difference.

So, I guess I'm missing something.

**Comment by rmyorston** [comment]
>So, I guess I'm missing something.

Me too, I guess.

Your `test.sh` script shouldn't cause a terminal to appear. I can't reproduce your problem on my system, so there must be some difference between our setups.

How are you starting the server? I'm running it from an interactive busybox-w32 shell with a command like:
```
httpd -p 8080 -h c:/users/rmy/www
```
where my web pages and `cgi-bin` directory are in `c:/users/rmy/www`.

What do you get if you add the command `which echo` to your script? It should just add `echo` to the output.

(Although `which` isn't a shell built-in it is a `NOEXEC` applet so it doesn't cause a terminal to appear either. A fact which I hadn't appreciated until I tried it. You can see which applets are `NOEXEC` and `NOFORK` by running `busybox --list-all`.)

**Comment by rmyorston** [comment]
Sorry, I was mistaken. Only `NOFORK` applets don't result in a terminal appearing. Using `command -v echo` instead of `which echo` should be OK.

**Comment by rmyorston** [comment]
The [latest prerelease binaries](https://frippery.org/files/busybox/prerelease) (PRE-5292 or above) should fix the issue with subprocesses of CGI scripts causing console windows to appear. (I hope.)

**Comment by rmyorston** [comment]
The most recent prereleases (PRE-5296 or above) also support `FEATURE_HTTPD_CONFIG_WITH_SCRIPT_INTERPR`. This extends the existing CGI support to allow web pages with a particular suffix to be processed by a script interpreter, typically PHP.

Since PHP is huge I made my own cut-down equivalent which replaces every instance of 'world' in a web page with 'PHP':
```sh
#!/bin/sh
echo "Content-type: text/html"
echo
sed 's/world/PHP/g' .$SCRIPT_NAME
```
The web server configuration file (which defaults to `/etc/httpd.conf`) needs to be told about this:
```
*.php:c:/users/rmy/php
```
And we need a web page, `hello.php`:
```
Hello world
```
Then we can do:
```
~ $ wget -q -S -O - http://localhost:8080/hello.php
  HTTP/1.1 200 OK
  Content-type: text/html

Hello PHP
```
Alternatively you can download the real PHP from [php.net](https://www.php.net). I unzipped my copy in `c:/users/rmy/php-8.3.2` and told the web server about it:
```
*.php:c:/users/rmy/php-8.3.2/php-cgi.exe
```
Note, you need to use the `php-cgi` binary and the `.exe` extension is required. It's also necessary to hack the PHP configuration:
```
~/php-8.3.2 $ sed 's/;cgi.force_redirect = 1/cgi.force_redirect = 0/' php.ini-production >php.ini
```
There are [reasons](https://www.php.net/manual/en/security.cgi-bin.force-redirect.php) for this which I didn't dig into too deeply. Since it's something to do with security anyone planning to use this probably should.

Then we need a really simple web page with some PHP in it:
```
<html>
<?php echo "Hello PHP\n"; ?>
</html>
```
And finally:
```
~ $ wget -q -O - -S http://localhost:8080/hello.php
  HTTP/1.1 200 OK
  X-Powered-By: PHP/8.3.2
  Content-type: text/html; charset=UTF-8

<html>
Hello PHP
</html>
```

**Comment by rmyorston** [comment]
Thanks for confirming the console window is no more.

The CGI and script interpreter features both come from upstream BusyBox. All I've done is implement some Windows code to support them.

**Comment by xparq** [comment]
Ahh, thanks! I made the mistake of searching for "cgi" on the [man page](https://busybox.net/downloads/BusyBox.html), rather than their home page...

**Comment by xparq** [comment]
Toying with PHP a little more, noticed a problem: with `busybox httpd -h bb-web` (having a `test.php` in `bb-web`), I get `No input file specified.` from PHP.

Starting the BB server with just `.../path/to/busybox httpd` (i.e. without `-h`), after `cd bb-web`, works fine.

Is `SCRIPT_FILENAME` set incorrectly with `-h`, perhaps?

**Comment by rmyorston** [comment]
Here's what I've been able to discover about `SCRIPT_FILENAME` and relative paths.

The comment about not "absolutizing" the path was introduced in commit 77e44d60e698c2164f610072e9f7e2bacefdd589. This contains a number of unrelated changes, but those relating to the path are intended to fix an [issue](http://lists.busybox.net/pipermail/busybox/2007-June/061668.html) raised on the upstream mailing list. Namely that the use of `realpath(3)` to "absolutize" the path was causing problems for CGI scripts when symbolic links were involved.

Slightly later commit 6bf05cf1ff3debbab2bcc482dffb821aa458177b made some further changes to improve the handling of relative paths. It also added the test which prevents `SCRIPT_FILENAME` from being set if the server root is a relative path.

The situation now is that since relative paths work properly in almost all cases there's no pressing _need_ to "absolutize" the server root set by the `-h` option. The only place "absolutizing" is required is when setting `SCRIPT_FILENAME` and this is now handled by simply rejecting a relative server root in this case.

I suspect the use of `realpath(3)` for `SCRIPT_FILENAME` could _probably_ be reintroduced without ill effects. However, there might be unintended consequences, so I'm not sufficiently confident to propose suggesting this upstream.

When this feature is released I'll add some documentation about `SCRIPT_FILENAME`.

**Comment by avih** [comment]
> this is now handled by simply rejecting a relative server root in this case.

Hmm. I'm not a user of httpd (I use my own server), but unless I'm misinterpreting something or unless typically relative root is allowed, I don't think it's generally nice to require absolute path for the root www dir...

I'm guessing the default root is the relative `.`? is that disallowed too?

**Comment by rmyorston** [comment]
A relative server root is only rejected for the purpose of setting `SCRIPT_FILENAME`.

**Comment by avih** [comment]
Yeah, I couldn't quite figure out when that happens, in the grand scheme of things. Is it set by busybox for any cgi script (looks like upstream sets it when the root is absolute?) ? optionally by the user in some use cases? etc

**Comment by rmyorston** [comment]
`SCRIPT_INTERPRETER` is set by the server when a CGI script or external interpreter is run.

It isn't one of the environment variables specified by the CGI [RFC](https://www.rfc-editor.org/rfc/rfc3875), but it _is_ required by PHP.

So if the server root is a relative path processing of PHP scripts in web pages will break.

**Comment by avih** [comment]
Thanks.

**Comment by xparq** [comment]
> Here's what I've been able to discover about SCRIPT_FILENAME and relative paths.

Thanks a lot for your investigation! Also, this issue is ripe for closing now, as far as I'm concerned.

**Comment by rmyorston** [comment]
I'm thinking about making a new release in the near future. I'd prefer to leave this issue open until after that's gone out.
