### ISSUE TITLE
What is the approach to determine the script's path cross-platform?

### ISSUE THREAD

**Issue by doctorpangloss** [rmyorston/busybox-w32#277]
I'm authoring a common header for scripts I use on Windows (in busybox64.exe), macOS (zsh) and Linux (bash), seeking to complete:

```shell
#!/usr/bin/env sh
SCRIPT_DIR=$(...)
```
where `SCRIPT_DIR` is the directory where the script is located. 

 - What is the approach to determine the script's path that will work on these 3 platforms, where Windows uses busybox64?
 - What is the approach for scripts meant to be sourced?

Currently, my workaround is using `git`, but this does not work from any working directory.

**Comment by rmyorston** [comment]
For a script that's being executed rather than sourced this _might_ work in _some_ cases:
```
SCRIPT_DIR=$(dirname $(realpath "$0"))
```
Though I don't know about zsh and MacOS.

See [How do I get the directory where a Bash script is located from within the script itself?](https://stackoverflow.com/questions/59895/how-do-i-get-the-directory-where-a-bash-script-is-located-from-within-the-script) for more ideas (though many of them involve bashisms).

**Comment by rmyorston** [comment]
The suggestion is:
```sh
wdir="$PWD"; [ "$PWD" = "/" ] && wdir=""
case "$0" in
  /*) scriptdir="${0}";;
  *) scriptdir="$wdir/${0#./}";;
esac
scriptdir="${scriptdir%/*}"
echo "$scriptdir"
```
Unfortunately this won't work on Windows. It relies on the Unix-specific assumption that an absolute path starts with a '/'. (I've written about how Windows [paths are different](https://frippery.org/busybox/paths.html).)

This is my attempt at a pure sh approach for Windows. (Warning: might be buggy.)
```sh
case "$PWD" in
	[a-zA-Z]:/)
		wdir="${PWD%%/*}"
		drive="${PWD%%/*}"
		;;
	[a-zA-Z]:/*)
		wdir="$PWD"
		drive="${PWD%%/*}"
		;;
	*)
		wdir="$PWD"
		drive=""
		;;
esac

case "$0" in
	[a-zA-Z]:/*) scriptdir="${0}";;
	//*) scriptdir="${0}";;
	/*) scriptdir="$drive${0}";;
	*) scriptdir="$wdir/${0#./}";;
esac
scriptdir="${scriptdir%/*}"
echo "$scriptdir"
```

**Comment by doctorpangloss** [comment]
I'll test this shortly on macOS and Linux.

**Comment by doctorpangloss** [comment]
> @rmyorston thanks for the great script. I ran couple of tests and seems working fine. Here I stripped your script
> 
> ```shell
> wdir="${PWD%/}"
> case "$wdir" in
>   [a-zA-Z]:*) drive="${wdir%%/*}";;
> esac
> case "$0" in
>   [a-zA-Z]:/*|//*) scriptdir="$0";;
>   /*) scriptdir="${drive}${0}";;
>   *) scriptdir="${wdir}/${0#./}";;
> esac
> scriptdir="${scriptdir%/*}"
> echo "$scriptdir"
> ```

This script produces incorrect results when `source`'d :(

**Comment by avih** [comment]
> I'm authoring a common header for scripts I use on Windows (in busybox64.exe), macOS (zsh) and Linux (bash), seeking to complete:
> 
> ```shell
> #!/usr/bin/env sh
> SCRIPT_DIR=$(...)
> ```
> 
> where `SCRIPT_DIR` is the directory where the script is located.

Depending on your needs, usually this is enough:
```sh
SCRIPT_DIR=$(dirname "$0") || >&2 echo cannot find scriptdir
```

The only "issue" with that is that it can end up relative. However, for the vast majority of cases that's perfectly fine, because most scripts don't need the dir of the original script after they've changed to a different directory, and if they didn't change directory, then relative is typically as good as absolute (obviously there can be exceptions, but they're not common IMO).

This also solves an issue where sometimes an absolute path is longer than `PATH_MAX`, and so it's not guaranteed that every relative dir can always be expressed as an absolute one which other tools can use.

If you really do need an absolute path, then this should work:
```sh
SCRIPT_DIR=$(cd -- "$(dirname "$0")" && pwd)  || >&2 echo cannot find scriptdir
```
Or this:
```sh
SCRIPT_DIR=$(cd -- "$(dirname "$0")" && printf %s\\n "$PWD") || >&2 echo cannot find scriptdir
```

All these solutions are POSIX compliant, simple, and should be portable enough.

They do have one unhandled edge case, like all scripts which do plain command substitution, and that's trailing newline[s] at the path (as uncommon as they might be) are eliminated. It could be solved like this, if you really care about it:
```sh
SCRIPT_DIR=$(cd -- "$(dirname "$0")" && printf %sx "$PWD") \
&& SCRIPT_DIR=${SCRIPT_DIR%x} \
|| >&2 echo cannot find scriptdir
```

The solutions mentioned in earlier posts (which do string processing of the value of `$0`) should also work, and may have an advantage that no additional processes are launched, which could be slightly faster, especially if used in performance-critical code. However, they're also less simple, and can have edge cases which needs handling.

Case in point - they don't handle backslashes in the path (simple to fix, but still needs fixing).

Additionally, if you don't use them in a subshell then they touch variables. And `local` is not portable. So if you want no side effects then you typically do need a subshell, which takes away their biggest advantage - speed because no processes are launched (subshell typically does launch a process). Alternatively, it's probably possible to place them in a function and use the positional parameters as temporary variables, which is more code and attention.

However, if you want the canonical absolute path of the script, then none of the solutions mentions so far would work, especially when it comes to directories which are symlinks.

So for the canonical path you need `readlink` or `realpath` - which are not POSIX and not portable, but also not uncommon (busybox and gnu systems do have them).

If you want `readlink` as a POSIX-compliant shell script, then you can try this https://github.com/ko1nksm/readlinkf .

**Comment by doctorpangloss** [comment]
The issue is resolved for non-sourced scripts, and it doesn't appear there is a general approach for sourced scripts.
