### ISSUE TITLE
/dev/urandom availability

### ISSUE THREAD

**Issue by mcoret** [rmyorston/busybox-w32#282]
Hi,

I know that there's a possibility to use /dev/urandom with dd utility in busybox, is it possible to extend the usage of the random device to other utilities, like cat and head (like it works in Linux)?

Thank you!

**Comment by rmyorston** [comment]
/dev/urandom in busybox-w32 works by intercepting the low-level I/O calls open(2)/read(2)/close(2). Allowing access to /dev/urandom from an applet requires the code to be audited to ensure it uses _only_ those functions. It's only allowed in a few places and only `dd` exposes that fact to the end user.

It would be possible to permit access to /dev/urandom from other applets. A quick look at `cat` suggests it wouldn't be too hard there. `head` would be trickier as it uses streams rather than file descriptors.

If usage of the random device were extended to other applets it would be necessary to document this. Currently the situation is very simple: the only way to access /dev/urandom from the command line is via `dd`. Allowing some, but not all, applets access would add uncertainty.

That said, if there are specific use cases which `dd` doesn't address it would be possible to look at them.

**Comment by ale5000-git** [comment]
Isn't simpler to add a new applet named urandom?
Then one could check its presence with `command -v urandom` and then pipe to everything, example: `urandom | cat`

**Comment by avih** [comment]
> Isn't simpler to add a new applet named urandom?

cute, and trivial to implement. nice.

> example: `urandom | cat`

useless use of cat? :)

**Comment by rmyorston** [comment]
There's no need for a new applet.  `dd if=/dev/urandom` serves the same purpose.

OK, it's a bit more to type, but it's portable.

**Comment by rmyorston** [comment]
Rummaging through closed issues I found #98: Please add /dev/urandom support in `od`.

This reminded me that back then some applets were able to open /dev/urandom and some weren't. This depended on an implementation detail of how the individual applets accessed files, so it wasn't obvious to the user which would work and which wouldn't.

It was as a result of #98 that use of /dev/urandom was limited to `dd`.

**Comment by rmyorston** [comment]
Seems reasonable. Try the [latest prerelease](https://frippery.org/files/busybox/prerelease) (PRE-5326 or above).

**Comment by rmyorston** [comment]
`/dev/urandom` and `/dev/zero` are now available for use as arguments to all applets and as sources for shell redirections. They're also visible to `ls` and `stat` if given as an explicit argument.

Prerelease binaries with this new feature are available in the [usual place](https://frippery.org/files/busybox/prerelease) (PRE-6067 or later).
