### ISSUE TITLE
vi editing mode makes busybox crash

### ISSUE THREAD

**Issue by PGcritter** [rmyorston/busybox-w32#283]
First of all thanks a lot for maintaining this wonderful utility which i use often on windows.

I think i have found a bug though. In "vi" editing mode, if i hit the following sequence of characters (in ash) , busybox just crashes:
```
<esc><slash><c><enter>
```
generally, search (/) is not working anymore (it used to). Let me know if more information is needed.

**Comment by rmyorston** [comment]
Interesting problem! I see what's happening but need to consider how best to fix it.

>generally, search (/) is not working anymore (it used to).

Are you sure about that? I wasn't aware that '/' ever worked in vi mode.

**Comment by PGcritter** [comment]
Mmh i tried and couldn't indeed get any of the 4 or 5 older versions i have lying around to search  successfully in vi mode. Sorry i was probably mistaking bb's behaviour with some other shell i had tried on windows. Perhaps it is better to disable search in vi mode rather than risk it causing crashes (for people with too much vi memory-muscle like myself) ?

**Comment by rmyorston** [comment]
This should be fixed in the most recent [prerelease](https://frippery.org/files/busybox/prerelease) binaries (PRE-4851 and above).

As I said, it was an interesting problem.

The original cause was the `read_key()` function. It's been wrong since the earliest days of busybox-w32: unlike the upstream version it didn't clear `errno` when it started.

When the vi-mode line editing code handles a 'c' or 'd' command it reads the next key stroke to determine what needs to be changed or deleted. If, for some reason, `errno` had a non-zero value at that point it wouldn't be reset by `read_key()`, the line editing code would see that and treat it as end-of-file. Hence the shell would exit.

Until the FRP-4621 release this was a fairly serious problem: if the previous command failed `errno` would be non-zero and any 'c' or 'd' command would cause the fault.

From FRP-4621 things got worse. It introduced a commit (1ee308c75) to work around a bug in Wine. In conjunction with an earlier commit (54d2ea4b47) to work around a bug in MSYS2/Cygwin this resulted in `errno` _always_ being set to `ENOSYS` at the start of new interactive command input. Thus 'c' and 'd' commands would _always_ fail.

That you were trying to perform a search made no difference: BusyBox vi-mode line editing silently ignores search commands.

**Comment by PGcritter** [comment]
So it was not even crashing, just seeing a bogus end-of-input ! I see this is fixed in the pre-release indeed; thank you Ron.
