### ISSUE TITLE
ConEmu and busybox64.exe bash interactions: BB_SKIP_ANSI_EMULATION=0 permanently resolves [A[B[C[D issue in ConEmu

### ISSUE THREAD

**Issue by doctorpangloss** [rmyorston/busybox-w32#287]
# Summary

In certain situations, ASCII control characters are emitted onto the shell prompt; unusual characters and misprinting appears; or other console glitches depending on the console and configuration used with `busybox64.exe bash`.

These can be categorized into two issues that can be found elsewhere on the Internet:
 - The **`[A[B[C[D`** issue: Hitting the arrow keys on the text prompt emits ANSI control characters instead of performing a typical arrow key keyboard input.
 - The **Music Note** issue: The shell emits music note character, dot characters and other ASCII representations of control code, and doesn't correctly clear output when performing arrow key, return and other similar keyboard inputs.

This ticket will focus on interactions between ConEmu and `busybox64.exe bash`.

# Description

When using `busybox64.exe bash -il` as the shell in ConEmu with its default settings, the [A[B[C[D issue manifests shortly after a subprocess exits with an error code 1 or higher.

**Observed issue**

Click thumbnail to start gif
![ConEmu64_gxvVyOkix8](https://user-images.githubusercontent.com/2229300/219459863-045a05c5-cda1-4807-9281-c56d7705e515.gif)

# Reproduction

 1. Install ConEmu
 2. Open it.
 3. Start `busybox64.exe bash`. Observe you are at the input for `sh` instead of `cmd`.
 4. Run a program that exits with error code 1. I use `git asdf`.
 5. Right after the program exits, observe you are at the shell. Immediately strike the arrow keys.
 6. Observe ANSI control characters for a short while. I should see cursor movement instead.
 7. Then, observe normal cursor movement resumes.
 8. Switch to XTerm emulation by clicking the small W in the bottom of the status bar of ConEmu.
 9. Observe ANSI control characters are always emitted when pressing the arrow keys.
 10. Switch back to Windows.
 11. Observe normal behavior.
 12. Click the Hamburger menu in ConEmu, select Features from the left hand side, then uncheck Inject ConEmuHk. Repeat steps 2 through 5. Observe instead that no ANSI control characters are emitted (correct behavior).
 13. Check Inject ConEmuHK. Repeat steps 2 & 3.
 14. Run `set BB_SKIP_ANSI_EMULATION=0`.
 15. Repeat steps 4 & 5. Observe the correct behavior: no emitted ANSI control sequences.

See related: https://github.com/Maximus5/ConEmu/issues/2266

This resolves issues where a process that exits with an error (for example, `git asdf`) will shortly print `[A[A[A[A` as you rapidly tap up arrow.

**Comment by rmyorston** [comment]
This issue and the ConEmu one mention a number of things I don't normally have configured in my Windows virtual machines:
- ConEmu
- SSH
- Midnight Commander
- git

I'm also not clear how busybox-w32 comes into the picture.

What's the minimum I need to install and do to reproduce the issue?

**Comment by doctorpangloss** [comment]
I updated the issue. Thanks for the attention. I am writing a second ticket re: ssh issues.

**Comment by rmyorston** [comment]
Thanks for the detailed description of the problem. I've now had a chance to investigate.

The issue with `git` is related to #223. It isn't about whether the command succeeds or fails, it's actually about the _kind of application_ it is. Git for Windows is built using MSYS2. It turns out MSYS2 applications alter the console settings in a way the busybox-w32 shell didn't expect.

As you've discovered, a workaround is to set `BB_SKIP_ANSI_EMULATION=0`. A more transparent workaround, one that doesn't require setting an environment variable, was introduced by commit 54d2ea4b47. Unfortunately this latter workaround doesn't work in ConEmu. I tried various hacks but nothing seems to help. I suspect ConEmuHK might be the root cause and there's nothing busybox-w32 can do about it.

In the circumstances I can only suggest either disabling ConEmuHK or setting `BB_SKIP_ANSI_EMULATION`. There are various ways to achieve the latter:
- Put `export BB_SKIP_ANSI_EMULATION=0` in `.profile` in your home directory. This will affect all busybox-w32 shells, though.
- Put `set BB_SKIP_ANSI_EMULATION=0` in the ConEmu environment. (Settings.../Startup/Environment from the hamburger menu.)
- Alter the startup command in ConEmu to include `sh -l -s -c "export BB_SKIP_ANSI_EMULATION=0"`.

As regards the XTerm setting in ConEmu, I've been unable to find a way to make busybox-w32 work correctly with it. It looks as though this is a strict XTerm implementation without any concessions to compatibility with Windows console applications. In contrast, the Cygwin terminal presents itself as an XTerm but busybox-w32 works well there. (OTOH, it doesn't work terribly well in the Git for Windows terminal, which is an MSYS2 version of the Cygwin terminal.)

**Comment by doctorpangloss** [comment]
> It turns out MSYS2 applications alter the console settings in a way the busybox-w32 shell didn't expect.
is there a way to figure out ahead of time if the application was compiled with MSYS2, and if so, apply the quirk automatically?

**Comment by rmyorston** [comment]
It seems I was too hasty in blaming MSYS2 applications for the problem: pretty much any  command is affected. Exceptions are:
- shell builtins: `true`, `false`, `pwd`, etc
- trivial built-in commands: `clear`, `printenv`, `uname`, etc
- MSYS2 applications of 2021 vintage(!), though not more recent ones.

I see there's another open issue about this type of problem: [https://github.com/Maximus5/ConEmu/issues/2316](https://github.com/Maximus5/ConEmu/issues/2316).

I've applied a hack in busybox-w32 so if we're running under ConEmu `BB_SKIP_ANSI_EMULATION` defaults to zero, thus forcing the use of emulation and avoiding the problem. It's still possible to set `BB_SKIP_ANSI_EMULATION` explicitly.

Try the latest prerelease binary: [busybox_pre64.exe](https://frippery.org/files/busybox/prerelease/busybox_pre64.exe).

**Comment by ale5000-git** [comment]
I'm not sure about the real performance benefit but wouldn't be worth skip the code: `is_wine() || getenv("CONEMUPID") != NULL`
if BB_SKIP_ANSI_EMULATION is set?
If I have read the code correctly the check is done also when not needed, and is_wine() load an external dll.

**Comment by rmyorston** [comment]
We can also change the order of the `is_wine()` and `getenv("CONEMUPID") != NULL` tests.

It probably won't make much difference to performance but there's no cost.

Done.

**Comment by doctorpangloss** [comment]
The issue is resolved in the latest pre-release binary.

Thanks for being so fastidious about these bugs. It's nice to get a payoff from a bug report for a great piece of software. Really should be everyone's daily driver console on Windows.
