### ISSUE TITLE
[Question] Why don't integrate the real GNU make?

### ISSUE THREAD

**Issue by tn1997tn** [rmyorston/busybox-w32#294]
Why did you integrate your pdpmake instead? If it's about licensing problems then I think BSD make is a better choice:

https://www.crufty.net/help/sjg/bmake.html

**Comment by rmyorston** [comment]
When writing `pdpmake` I had two aims in view:
- Strict POSIX compatibility
- The possibility of including it in busybox-w32

I started with an existing public domain clone of Unix v7 make, the common ancestor of all modern makes. This allowed me to add only the more recent features required for POSIX compatibility. (Some extensions were also added, but in a controlled manner to keep them separate from the strict POSIX features.)

Starting with code from GNU or BSD would have required separating POSIX from non-POSIX features, which are entangled in these implementations.

Also, alluded to above, GNU make has been GPLv3 since 2007. This is incompatible with BusyBox, which is GPLv2-only.

**Comment by tn1997tn** [comment]
> When writing `pdpmake` I had two aims in view:
> 
> * Strict POSIX compatibility
> * The possibility of including it in busybox-w32
> 
> I started with an existing public domain clone of Unix v7 make, the common ancestor of all modern makes. This allowed me to add only the more recent features required for POSIX compatibility. (Some extensions were also added, but in a controlled manner to keep them separate from the strict POSIX features.)
> 
> Starting with code from GNU or BSD would have required separating POSIX from non-POSIX features, which are entangled in these implementations.
> 
> Also, alluded to above, GNU make has been GPLv3 since 2007. This is incompatible with BusyBox, which is GPLv2-only.

What about this? http://bsdbuild.hypertriton.com/
