### ISSUE TITLE
Confused about the mechanics of double-quotes when `bb`  is run via (8.1) cmd.exe and escaping in this one-liner

### ISSUE THREAD

**Issue by garoto** [rmyorston/busybox-w32#305]
I'm always struggling/trying to figure out how to escape Win/POSIX reserved chars with a `busybox-w32` (and any *nix tool port really) binary when invoked with a somewhat busy command-line that may clash with `cmd.exe` own quote processing. Check this out:

```sh
[ C:\Users\garoto ]
[Thu, 18:45:05] > busybox sh -x -c "cat r:/words.txt | while read line; do printf \"[%s %s] %s\n\" $(date \"+%d-%m-%Y %H:%M:%S\") \"$line\" ; done"
+ cat r:/words.txt
+ read line
+ date '+%d-%m-%Y %H:%M:%S'
+ printf '[%s %s] %s\n' 30-03-2023 18:45:13 'Nowhere is it disputed that some posit the bonism cheese to be less than doleful'
[30-03-2023 18:45:13] Nowhere is it disputed that some posit the bonism cheese to be less than doleful
+ read line
+ date '+%d-%m-%Y %H:%M:%S'
+ printf '[%s %s] %s\n' 30-03-2023 18:45:13 'They were lost without the dusky apple that composed their cathedral'
[30-03-2023 18:45:13] They were lost without the dusky apple that composed their cathedral
+ read line
+ date '+%d-%m-%Y %H:%M:%S'
+ printf '[%s %s] %s\n' 30-03-2023 18:45:13 'The clingy credit comes from a svelter doctor'
[30-03-2023 18:45:13] The clingy credit comes from a svelter doctor
+ read line
```

Notice how the escaped double-quotes in my `cmd.exe` entry are replaced by single-quotes in the debug(?) output of busybox-w32 shell (OT, but Arriving at this specific command line and escaping syntax took me many hours across two different days, lol).

This is not a bug report, just trying to understand if there's something obvious regarding parsing of single-quotes and/or double-quotes that I'm missing (I'm not really familiar with POSIX/Linux shell behavior regarding quotes as well, so there's that).

edit: `words.txt` contents:
```
Nowhere is it disputed that some posit the bonism cheese to be less than doleful
They were lost without the dusky apple that composed their cathedral
The clingy credit comes from a svelter doctor
```

**Comment by rmyorston** [comment]
I don't think there's anything obvious you're missing: nothing about command line processing in Windows or the POSIX shell is obvious!

(The single quotes in the debug output are just a convention the shell uses. By the time it comes to print the debug output the original method used to quote arguments has been forgotten so it always uses single quotes.)

When busybox-w32 is run from cmd.exe it interprets its arguments according to the [standard rules](https://learn.microsoft.com/en-us/cpp/cpp/main-function-command-line-args?view=msvc-170&viewFallbackFrom=vs-2019#parsing-c-command-line-arguments) for a Windows executable.

Now, the string to be executed by the shell (what follows `-c`) has to be a single argument. We therefore have to use the rules to ensure that. They tell us (among other things):

>A string surrounded by double quote marks is interpreted as a single argument, which may contain white-space characters. ...

>A double quote mark preceded by a backslash (\") is interpreted as a literal double quote mark (").

We thus see that your quoting will achieve the desired result and treat the argument following `-c` as a single string:
```
"cat r:/words.txt | while read line; do printf \"[%s %s] %s\n\" $(date \"+%d-%m-%Y %H:%M:%S\") \"$line\" ; done"
```
The whole string is enclosed in double quotes and internal double quotes have been escaped with a backslash so they're treated literally. The string that's passed to the shell is:
```
cat r:/words.txt | while read line; do printf "[%s %s] %s\n" $(date "+%d-%m-%Y %H:%M:%S") "$line" ; done
```
This is exactly what's needed. Since single quotes have no special meaning in Windows this would also work:
```
"cat r:/words.txt | while read line; do printf '[%s %s] %s\n' $(date '+%d-%m-%Y %H:%M:%S') \"$line\" ; done"
```
The quotes around `$line` have to be double quotes (or the shell won't expand the variable) but when a literal string is being quoted it's probably easier to use single quotes.

It's a good thing you didn't have any wildcards in your arguments. That's an entirely different can of worms!

**Comment by garoto** [comment]
> (The single quotes in the debug output are just a convention the shell uses. By the time it comes to print the debug output the original method used to quote arguments has been forgotten so it always uses single quotes.)

Ah, that was my beef. While trying to troubleshoot my escaping syntax, `set -x` wasn't really helping, since I assumed it'd print verbatin the syntax the user entered, but ofc, your explanation seems to make perfect sense from the shell perspective.

> Since single quotes have no special meaning in Windows this would also work:

Yep, that also works indeed. In hindsight, I don't know why I struggled so much, I guess the original cmdline I borrowed from a bash perspective had double-quotes around the `date` call and that through me off a bit when trying to adapt it to my own use-case.

Thanks for the detailed response, very enlightening.
