### ISSUE TITLE
git content to less, pagedown & end, conemu and busybox interact poorly

### ISSUE THREAD

**Issue by doctorpangloss** [rmyorston/busybox-w32#306]
![ConEmu64_cAiyYRx8pK](https://user-images.githubusercontent.com/2229300/229577251-bb49b1b9-91b9-43e5-aad4-72259cb8b375.gif)

# Reproduction

 1. Clone a large `git` repo.
 2. Search its contents in the shell.
 3. Observe less is started. Hit `End`.
 4. Observe the terminal is glitched.
 5. Hit Ctrl+C.
 6. Observe the terminal is glitched. The status bar shows less.exe is still running, but you are interacting simultaneously with the shell and less.
 7. Carefully write `pkill less` to kill less.
 8. Observe the terminal is back in a normal state.

Reproducing on this repository:
```
git clone git@github.com:rmyorston/busybox-w32.git
cd busybox-w32
git rev-list --all | xargs git grep main.c
```

Then hit `End`. Then, good luck :)

**Comment by rmyorston** [comment]
Please try the latest [prerelease](https://frippery.org/files/busybox/prerelease).

There have been some changes to how Ctrl-C is handled. In this case `less` no longer responds to Ctrl-C so it can't shut down unexpectedly and leave the terminal in a weird state.

I should add, it wasn't my _intention_ to prevent `less` from handling Ctrl-C, it just seems to have happened as a side effect.

**Comment by doctorpangloss** [comment]
The issue still occurs. This time, I press Ctrl-C multiple times to trigger it.

**Comment by rmyorston** [comment]
OK, there's another new [prerelease](https://frippery.org/files/busybox/prerelease) which might help.

Things I've noticed:
- The problem is really nothing to do with ConEmu or with going to the end of the output.
- What's happening is that the instances of `git` and `less` started by `xargs` aren't being shut down when Ctrl-C is pressed.
- Even on Windows (with Git for Windows `bash`) and Linux the command has the same problem, though it's less severe in these cases because the surplus `git` and `less` shut down after a while when they notice the pipeline is broken.
- The fix I've applied is to have `xargs` shut down its child processes when it receives the interrupt.
- This works with the default `git` configuration or if Windows' `more` is specified as the pager. With busybox-w32 or Git for Windows `less` explicitly configured the Ctrl-C doesn't interrupt them.
   ```
   [core]
	#pager = c:\\\\windows\\\\system32\\\\more.com
	#pager = c:/users/rmy/busybox.exe less
	#pager = c:/Program\\ Files/Git/usr/bin/less.exe
   ```

**Comment by doctorpangloss** [comment]
Okay, now hitting Ctrl+C no longer quits `less` (i.e. git for Windows less) and I must hit q to exit. This matches expectations with POSIX `less`.
