### ISSUE TITLE
su interacts poorly with GUIs, opening a new window instead of using the currently attached console

### ISSUE THREAD

**Issue by doctorpangloss** [rmyorston/busybox-w32#314]
# Reproduction

 1. Open busybox sh in conemu.
 2. Run `su`.
 3. Observe a Windows cmd Window opens. This is unexpected. Close it.
 4. Run `sudo sh -li` using `sudo` from `choco install -y gsudo`.
 5. Observe an elevated shell is attached to the current console, as expected.

## Version
```
BusyBox v1.37.0-PRE-4908-gd9e8bb61c (2023-03-19 10:35:33 GMT)
```

**Comment by rmyorston** [comment]
busybox-w32 `su` is behaving as documented in the [release notes](https://frippery.org/busybox/release-notes/FRP-3023.html) for FRP-3023.

While the technology behind `gsudo` is intriguing, I note that `gsudo.exe` is 5.6M in size. The `su` applet in busybox-w32 adds 384 bytes to the binary.

**Comment by avih** [comment]
So I was trying to write a sudo script/function, but it seems that `su -c` fails in some cases where `sh -c` works. That's my function:

```sh
sudo() {
    su -c "( $(
        # shell-quoted string of "$@", fit for sh -c "$string"
        for v; do
            printf "'"
            printf %s "$v" | sed "s/'/'\\\\''/g"
            printf "' "
        done
    ));"' e=$?; echo "[Exit $e; ENTER to close]"; read x; exit "$e"'
}
```

This invocation `sudo ls no-such-file` ends up using this string (printed if replacing `su -c` with `echo`):
```
( 'ls' 'no-such-file' ); e=$?; echo "[Exit $e; ENTER to close]"; read x; exit "$e"
```

However, the output window looks like this:
```
ls: no-such-file: No such file or directory
[Exit
#
```
(the last line is the shell prompt waiting for some command)

So something aborted around where `$e` should have been printed, and looks like `read x` and `exit` were not reached.

Same result but as an actual command to copy-paste at the prompt:
```sh
su -c '(ls no-such-file); e=$?; echo "[err $e; press enter]"; read x; exit "$e"'
```

In both cases (the function and the direct command line) replacing `su -c` with `sh -c` makes it work correctly.

I _think_ this could point at some windows quoting incompatibility someplace, but it's not clear to me where. I think that busybox-w32 does quote correctly, because a trivial C program which prints its arguments does show a correct argument value. So maybe a `cmd.exe` incompatibility someplace?

**Comment by avih** [comment]
> busybox-w32 su is behaving as documented in the release notes for FRP-3023.

Your link works, but it's not actually linked from the release notes page: https://frippery.org/busybox/release-notes/

Also, maybe all the notes can be combined to a single file? it's effectively impossible to figure out how `su` should behave by fishing a random release note which is not even linked from anywhere that I can tell (other than this issue)...

**Comment by rmyorston** [comment]
The command passed to the shell goes through Microsoft's pathetic excuse for command line parsing.

Try this:
```
su -c '(ls no-such-file); e=$?; echo \"[err $e; press enter]\"; read x; exit \"$e\"'
```
The FRP-3023 release notes aren't linked because they were superseded by [FRP-3025](https://frippery.org/busybox/release-notes/FRP-3025.html) the next day. The latter includes all the FRP-3025 content.

**Comment by avih** [comment]
> Try this: ...

Should this be considered a busybox issue?

If not, what's the general rule here to correctly quote an arbitrary value?

**Comment by avih** [comment]
> I note that `gsudo.exe` is 5.6M in size

I found these seemingly unrelated programs `elevate`, which both presume to be sudo-like, and both include (C) source and binary. The sources seem fairly small, and the binaries too.

I downloaded both and looked very briefly at the main c files, but that's about it so far.

http://code.kliu.org/misc/elevate/
https://jpassing.com/2007/12/08/launch-elevated-processes-from-the-command-line/

**Comment by doctorpangloss** [comment]
I really appreciate the attention on the issue.

> `su -c '(ls no-such-file); e=$?; echo \"[err $e; press enter]\"; read x; exit \"$e\"'`

In conemu and cmd, this creates a new window. When I ssh into the machine, nothing happens.

>  Both open a new elevated cmd.exe window, pretty much like bustbox-w32

Yes, I really wonder why this is the behavior. 

> While the technology behind gsudo is intriguing

Lemme investigate it too. I chose `gsudo` because it does work the best, most consistently. I agree it is large and not a good fit. But it was the closest to a consistent "native" "Unix" experience. As always I advocate for busybox.exe everywhere.

**Comment by rmyorston** [comment]
>Should this be considered a busybox issue?

Probably. The alternative is to say it's a Microsoft issue, but we all know that isn't going to lead to a satisfactory outcome.

>If not, what's the general rule here to correctly quote an arbitrary value?

There are two things going on:
- In the command `su -c "command stuff"` the `command stuff` has to be quoted to make it a single argument.
- Inside `su` the `command stuff` is quoted (using double quotes) so the Microsoft command line parsing treats it as a single argument. Any double quotes in the `command stuff` need to be escaped with a backslash to prevent them from causing the argument to be split. Single quotes in `command stuff` are fine because they mean nothing to the Microsoft parser.

The trick is to create a string that meets both these requirements and still ends up being the command you wanted once it hits the elevated shell.

**Comment by rmyorston** [comment]
>> Both open a new elevated cmd.exe window, pretty much like bustbox-w32

>Yes, I really wonder why this is the behavior.

All three are using the same technique, a call to `ShellExecuteEx()`, and that's just how `ShellExecuteEx()` works.

This also explains why it doesn't work when you use ssh: the remote machine is unable to start a new window on the local machine.

**Comment by avih** [comment]
> Try this:
> 
> ```
> su -c '(ls no-such-file); e=$?; echo \"[err $e; press enter]\"; read x; exit \"$e\"'
> ```

Assuming it does work (didn't try), I don't get why.

The [docs](https://learn.microsoft.com/en-us/windows/win32/api/shellapi/ns-shellapi-shellexecuteinfoa) say:
> To include double quotation marks in lpParameters, enclose each mark in a pair of quotation marks, as in the following example: `sei.lpParameters = "An example: \"\"\"quoted text\"\"\"";`  In this case, the application receives three parameters: An, example:, and "quoted text".

So presumably literal dquotes should be quoted inside dquote (... whatever), and the docs doesn't mention any other special chars that I can tell.

But in your example they're backslash-escaped.

So does backslash have special meaning in `lpParameters` ? should it be escaped too?

**Comment by doctorpangloss** [comment]
I've observed other apps opening GUIs when unexpected. For example, including the Avalonia UI libraries in a `dotnet` project building to `Exe` (i.e. a command line application). There are definitely flawed Windows apps.

**Comment by ale5000-git** [comment]
All apps open a new window when rquest elevation because if it what Microsoft choose.
The one that doesn't need it probably are using tricks that may be broken by updates of Windows.
