### ISSUE TITLE
`ps`: command column  could have more space

### ISSUE THREAD

**Issue by naksyl** [rmyorston/busybox-w32#358]
Comparing to posix win32 executables tends to have longer names. Acceptable solutions:
- doubling the width should be enough 
- apply fit terminal width strategy - as upstream do
- hardcode line width to 80

```sh
$ ps -o comm | grep -v 'exe$' | awk 'length() >= 15' | sort | uniq
AggregatorHost.
ApplicationFram
CAudioFilterAge
FileSyncHelper.
GameBarFTServer
IntelCpHDCPSvc.
IntelCpHeciSvc.
LocationNotific
Memory Compress
NVDisplay.Conta
OneApp.IGCC.Win
PresentationFon
RstMwService.ex
RtkBtManServ.ex
RuntimeBroker.e
SearchIndexer.e
SearchProtocolH
SecurityHealthS
ShellExperience
StartMenuExperi
SynTPEnhService
SystemSettings.
SystemSettingsB
TextInputHost.e
UserOOBEBroker.
WidgetService.e
WindowsTerminal
[System Process
backgroundTaskH
igfxCUIService.
msedgewebview2.
```

edit:
`[` typo in [System Process? - oh I get it no place for `]`

**Comment by rmyorston** [comment]
Sounds reasonable. I've increased the buffer to 32 characters.
- Upstream BusyBox is limited to 16 characters because that's what Linux reports (for example, in `/proc/<PID>/comm`).
- There are two fields that have the `COMMAND` header: `comm` and `args`. When `ps` is run without the `-o` option it displays `args`. This isn't truncated, but on Windows it usually displays the same value as `comm`.
- Using 32 characters for `comm` might confuse scripts that try to parse the output of `ps`. Such scripts are likely to be non-portable so this shouldn't be too big a problem. If necessary `ps` could be made to truncate the `comm` output at 16 characters while still displaying 32 for `args`.

You know where to find the prereleases, I expect.

**Comment by naksyl** [comment]
> You know where to find the prereleases, I expect.

Yes, actually I am trying to write a script which replace running busybox (old trick with rename exe + exec not sure if it can work yet) with bleeding edge - kind of `busybox --update`
