### ISSUE TITLE
[question] Default applet (ash) ?

### ISSUE THREAD

**Issue by naksyl** [rmyorston/busybox-w32#359]
Why busybox does not have default applet? Am I missing something here? 

Recently I download a few prerealese versions. It could be a handy feature to double click `busybox*.exe` from `explorer` or `browser downloads` and go straight to the shell

edit:
oh busybox is default, run after exe name. Closing

**Comment by rmyorston** [comment]
If you copy (or link) the binary to `sh.exe` double clicking on that will start a shell.

However, since the shell gets no arguments it doesn't behave as a login shell. This means:
- it doesn't switch to the user's home directory
- it doesn't run any profile scripts

I've added `lash` as an alias for `ash`. If the binary is copied to `lash.exe` double clicking it will start a login shell. (Commit 2af141a2c069c56d56f110414f600f3a38ad8617)

This doesn't really help with your collection of prerelease binaries. `busybox_version_string.exe` will happily work as BusyBox but `sh_version_string.exe` won't do anything very interesting.
