### ISSUE TITLE
`ash` - hidden system files and globbing

### ISSUE THREAD

**Issue by naksyl** [rmyorston/busybox-w32#367]
Recent release add support for hiding files with `system` attribute (`ls -AA`). This reminds me that globbing show files with `hidden` attribute wich I belive shoud be treated as Unix dotfiles (ls does not show them)
```sh
~ $ ls | grep -i ^nt

~ $ printf "%s\n" * | grep -i ^nt
NTUSER.DAT
NTUSER.DAT{a2332f18-cdbf-11ec-8680-002248483d79}.TM.blf
NTUSER.DAT{a2332f18-cdbf-11ec-8680-002248483d79}.TMContainer00000000000000000001.regtrans-ms
NTUSER.DAT{a2332f18-cdbf-11ec-8680-002248483d79}.TMContainer00000000000000000002.regtrans-ms
ntuser.dat.LOG1
ntuser.dat.LOG2
ntuser.ini

~ $ lsattr nt* NT*
------hsa-- ntuser.dat.LOG1
------hsa-- ntuser.dat.LOG2
------hs--- ntuser.ini
------h-a-n NTUSER.DAT
------hsa-- NTUSER.DAT{a2332f18-cdbf-11ec-8680-002248483d79}.TM.blf
------hsa-- NTUSER.DAT{a2332f18-cdbf-11ec-8680-002248483d79}.TMContainer00000000000000000001.regtrans-ms
------hsa-- NTUSER.DAT{a2332f18-cdbf-11ec-8680-002248483d79}.TMContainer00000000000000000002.regtrans-ms
```

**Comment by rmyorston** [comment]
The shell now has (non-standard) options to control how the hidden and system attributes affect globbing:
- `nohiddenglob` excludes files with the hidden attribute from globbing
- `nohidsysglob` excludes files with both the hidden and system attributes

Note:
- `nohiddenglob` takes precedence.
- The options also affect tab completion.
- The options don't affect the treatment of files that are hidden only because they start with a period. (If such files also have the hidden attribute set they _are_ affected).

An example of the use of the new options (plus the existing `nocaseglob`):
```
~ $ set -o nocaseglob
~ $ lsattr nt*
------h-a-n NTUSER.DAT
------hsa-- NTUSER.DAT{53b39e88-18c4-11ea-a811-000d3aa4692b}.TM.blf
------hsa-- NTUSER.DAT{53b39e88-18c4-11ea-a811-000d3aa4692b}.TMContainer00000000000000000001.regtrans-ms
------hsa-- NTUSER.DAT{53b39e88-18c4-11ea-a811-000d3aa4692b}.TMContainer00000000000000000002.regtrans-ms
------hsa-- ntuser.dat.LOG1
------hsa-- ntuser.dat.LOG2
------hs--- ntuser.ini
~ $ set -o nohidsysglob
~ $ lsattr nt*
------h-a-n NTUSER.DAT
~ $ set -o nohiddenglob
~ $ lsattr nt*
lsattr: can't stat 'nt*': No such file or directory
~ $
```

**Comment by naksyl** [comment]
> The options also affect tab completion.

Nice surprise.
