### ISSUE TITLE
Directory */ glob not working in shell script

### ISSUE THREAD

**Issue by otpfiste** [rmyorston/busybox-w32#381]
Hi,

a simple script like the following should only return folders, but it returns also regular files. I tested it in a busybox under Ubuntu, and there it works correctly.

```
#!/bin/sh
for folder in */
do
    printf '%s\n' "$folder"
done
```
All the best,
Oliver

**Comment by rmyorston** [comment]
Which version of busybox-32 are you using? (`busybox | head -1`)

I'm unable to reproduce the problem in the current release.

**Comment by otpfiste** [comment]
I use:
BusyBox v1.37.0-FRP-5236-g7dff7f376 (2023-12-06 10:31:32 GMT)

I made some more test and found out that the problem only happens when running the script in a NAS network share mounted as a drive.

**Comment by rmyorston** [comment]
Thanks for the additional information. This allowed me to reproduce the problem and track down the cause.

It turns out the WIN32 API being used to detect that files weren't directories works differently on a network share than on an actual disk.

The issue should be fixed in the latest [prerelease](https://frippery.org/files/busybox/prerelease) binaries. (PRE-5254 or above)

**Comment by otpfiste** [comment]
Hi,

I tested it, it works great, many thanks for the fast fix!!

All the best
