### ISSUE TITLE
Unicode support on old Windows + other questions

### ISSUE THREAD

**Issue by 636C6F776E** [rmyorston/busybox-w32#386]
First, thank you for porting BusyBox to Windows. It's a great lightweight replacement to MSYS2. BusyBox has become my new favorite shell, replacing the venerable *cmd.exe*.

Second, sorry for using the Issues forum to start this topic but I'm not yet aware of a better location for it.

1. My problem is I'm using Windows 7 and do not want to upgrade to 10. It seems strange to me that *busybox64u.exe* requires Win10 or later. Even good old Windows XP has Unicode support and it is vital for a program to be able to handle Unicode filenames. Out of curiosity I would like to know how come the requirements for supporting Unicode are so high. Why Windows 10?

2. I would like to customize the BusyBox shell with a `~/.profile` file. However that requires passing the `-l` parameter which in turn changes the working directory to the `$USERPROFILE`. Is it possible to load the profile without changing directory? Equivalent option in MSYS2: `CHERE_INVOKING=1`.

3. I've noticed that BusyBox likes to replace all backslashes `\` with forward slashes `/`. That wouldn't be a problem if not for the fact that it's applied to environment variables as well. So if I tried to be "clever" and define an environment variable:
`PS1='[\[\e[1;34m\]\W\[\e[m\]] \$ '`
it will be mangled by BusyBox into the nonsensical:
`PS1='[/[/e[1;34m/]/W/[/e[m/]] /$ '`
This will be a non-issue if problem no. 2 is solvable.

Thank you for your time and I'm looking forward to future releases!

**Comment by rmyorston** [comment]
>Why Windows 10?

Not just Windows 10, Windows 10 Version 1903 and above.

The mechanism used for UTF-8 support is a [manifest](https://learn.microsoft.com/en-us/windows/apps/design/globalizing/use-utf8-code-page). This makes UTF-8 available without having to fiddle with wide-character APIs, which would have required much more work.

Unfortunately the manifest is only supported in recent versions of Windows. Indeed, Windows XP refuses to run applications with the UTF-8 manifest.

An alternative way to read a profile in a non-login shell is to set the `ENV` environment variable to point to a script. Any interactive shell will run this on startup. `ENV` is specified in POSIX and works in the busybox-w32 shell.

The shell option `-X` prevents the conversion of backslashes to forward slashes in environment variables.

**Comment by rmyorston** [comment]
For further information on UTF-8 and the `-X` shell option, see the release notes for [FRP-5181](https://frippery.org/busybox/release-notes/FRP-5181.html). It's a coincidence that both those items happen to be mentioned in the same release.

The release notes are recommended reading for anyone with a serious interest in busybox-w32.

**Comment by 636C6F776E** [comment]
Thank you for the quick reply! `ENV` was exactly what I needed!
Also thanks for `BB_OVERRIDE_APPLETS` which I've put to use.

**Comment by 636C6F776E** [comment]
@avih No, I am not. Maybe there is a misunderstanding: my `PS1` backslash problem was caused by me defining `PS1` as an environment variable in Windows.

Computer (right-click) -> Advanced system settings ->Advanced -> Environment Variables...

**Comment by avih** [comment]
> was caused by me defining `PS1` as an environment variable in Windows.

Ah, right, that would indeed convert `\` to `/`. Thanks.

Out of curiosity, why not set that in your `~/.profile` instead?

Regardless though, I still think PS1 should be excluded from this conversion, like some other vars names are.

**Comment by 636C6F776E** [comment]
> Out of curiosity, why not set that in your `~/.profile` instead?

Because I use BusyBox from Total Commander and open it directly in the current folder.
Equivalent functionality in Linux: Krusader opening Konsole with "F2 Term" or "F9 Term".

> Regardless though, I still think PS1 should be excluded from this conversion, like some other vars names are.

That doesn't affect me right now. What does affect me is Unicode chars in filenames. For now I'm happy with what I have.

**Comment by sergeevabc** [comment]
Aggrrhh! I cannot grep and copy files with results via Busybox on Windows 7.

``` console
$ busybox ls
Томас Дилан 1914-1953.md     Шекспир Уильям 1564-1616.md

$ file "Шекспир Уильям 1564–1616.md"
Шекспир Уильям 1564-1616.md: Unicode text, UTF-8 text, with CRLF, LF line terminators

$ busybox cat "Шекспир Уильям 1564–1616.md"

---
tags: [Notebooks/Р│РёС'Р°С'С<]
---

# РЁРчРєС?РїРёС? Р?РёР>С?С?Р? 1564в?"1616

## 1609. Hamlet

* If the authorities knew about the problems and chose not to prevent them, then clearly something is rotten in the state of Denmark.
```

Since the required file has UTF-8 encoding, its non-Latin part is displayed incorrectly.

``` console
$ chcp 65001

$ busybox cat "Шекспир Уильям 1564–1616.md"

---
tags: [Notebooks/Цитаты]
---

# Шекспир Уильям 1564–1616

## 1609. Hamlet

* If the authorities knew about the problems and chose not to prevent them, then clearly something is rotten in the state of Denmark.

```

Now it's looking as expected. We're ready to grep.

``` console
$ busybox grep Цитаты *.md
```

Oops. No results. Yet it works with Latin, however the results are displayed incorrectly.

``` console
$ busybox grep Hamlet *.md
������� ������ 1564�1616.md:## 1609. Hamlet
```

Right, let's grep with another tool then.

``` console
$ rg -l0 Цитаты
Шекспир Уильям 1564–1616.md
```

Good. And I want to copy that file to another folder…

``` console
$ rg -l0 Цитаты | busybox xargs -t -0 cp -t C:\123

cp -t C:\123 Шекспир Уильям 1564–1616.md
cp: can't stat 'Шекспир Уильям 1564–1616.md': No such file or directory
```

Does not work, because Busybox still cannot play nice with Unicode on Windows 7, whereas many other modern utils surprisingly can. But wait a second, there is `iconv` applet.

``` console
$ rg -l0 Цитаты | busybox iconv -f UTF-8 -t CP1251 | busybox xargs -t -0 cp -t C:\123

cp -t C:\123 ������� ������ 1564�1616.md

$ busybox ls C:\123
������� ������ 1564�1616.md

$ chcp 1251

$ busybox ls C:\123
Шекспир Уильям 1564–1616.md
```

Finally, the file has been copied. But all the frustration with encoding along the way!

**Comment by sergeevabc** [comment]
> There's no native Unicode support in busybox-w32.

@avih, it's like discovering the betrayal of a woman you love, it breaks my heart.
Come on, computers were invented to help people, to ease the burden.
Coreutils, for example, works fine with Unicode on Windows 7, but it has no `xargs`.

**Comment by avih** [comment]
It's open source. Feel free to contribute native Unicode support to busybox-w32.

If you care, I contributed the trick thing with win10+, and even that was not simple at all. I also want/wanted to add native Unicode support, but it's much harder than using the trick, so it's on hold probably forever.

But maybe you can do that.

**Comment by sergeevabc** [comment]
> But maybe you can do that.

It's beyond my expertise. I observe life, report its dragons and look for heroes to defeat them. For example, meet Doug Cook aka @idigdoug, who developed [wargs](https://github.com/idigdoug/TextTools) (xargs for Windows). Look how neat is to have `-f utf8` switch. From its manual:

``` console
$ wargs -h

...

-f ENCODING, --from-code=... Encoding of input. Use NNN, cpNNN, utf8,
                             utf8bom, utf16, utf16bom, utf16be, etc.
                             Default: cp0bom (CP_ACP unless BOM present).
...

ENCODING names ignore case and punctuation (e.g. 'utf-8' is the same as
'UTF8'). They may be formatted as digits (Windows code page identifier), 'CP'
followed by digits, or 'UTF' followed by '8', '16', '32', '16LE', '16BE',
'32LE', or '32BE'. Input encodings may have a 'BOM' suffix indicating that if
the input starts with a BOM, the BOM should be consumed and the corresponding
UTF encoding should override the specified encoding.
```

Now let's apply it to the case I reported above.

``` console
$ rg -l0 цитаты | wargs -f utf8 -0 busybox cp -t c:\123

$ busybox ls C:\123
Шекспир Уильям 1564–1616.md
```

Win!

Why not add `-f ENCODING` to Busybox? Wargs code is open-sourced.

**Comment by avih** [comment]
> Why not add `-f ENCODING` to Busybox `xargs` applet?

Why not also applets foo and bar?

I can't speak for the maintainer, but I'd think because it's not worth the effort and potential complexity for the few remaining win7 users.

IMO either everything becomes native Unicode, and good lock with that, or it is what it is for win7 users.

**Comment by idigdoug** [comment]
Funny that I should be added to this thread. I use busybox-w32, and I had read through this thread before. Thanks for all the good work. Busybox-Unicode isn't very important to me, but I would be willing to help.

In the past, whenever I've had a Windows program that needs to support Unicode, I've always done the following:

- Within the program, the encoding doesn't matter as long as it is well-defined and consistent, the encoding uses 0..127 for ASCII, and all hard-coded CHAR constants are ASCII.
- Whenever talking to Windows or CRT APIs, always use the WCHAR version of the API. Convert from your internal encoding to UTF-16LE, call the API, convert the results back to your internal encoding.
  - Exception: if the parameter is data content, like the content of a file or the content being read-from/written-to a pipe, the data should not be converted.

Starting in Windows 10, you can use the manifest to make Windows do this automatically for all Windows APIs, but it only works in Windows 10 and it can't be changed at runtime. There are also some issues with the CRT APIs that are present even if you set this manifest. I don't know if they are all resolved.

If we were to switch to a better system, the advantages would be:
- Able to configure at runtime, so only one binary is needed for both ANSI and UTF-8 modes.
- Able to work on older versions of Windows.
- Solid fix for CRT APIs (not sure if there are any here, but I know there used to be some).

If busybox-w32 maintainers think this is a worthwhile feature, I would be willing to help with it. However, I would need help from maintainers, so the maintainers would need to decide whether this is worth doing.

**Comment by avih** [comment]
> needs to support Unicode, I've always done the following:

Yes. This is the normal "do unicode on windows thing". But this is a big project, and it's not mainly windows. busybox-w32 is a set of (many) patches on top of essentially linux codebase. So we can't make this whole codebase use wchar_t etc, because the whole internal code uses char*.

It is possible to wrap the "edges" to use W windows APIs, and convert everything immediately to utf8 so that internally it can remain char*, and back from char* to wchar_t at the edges.

This is basically the big effort that I've put on hold because it's not easy at all. The problem is not how to do unicode on windows. It's how to do that with linux code inside.

And we can't change the inside to be windows W APIs, because if we do that then it would be impossible to keep taking the updates of upstream busybox. So the internals have to stay largely unmodified.

> * Able to configure at runtime, so only one binary is needed for both ANSI and UTF-8 modes.

That's not required. If it's correct native unicode then there's no meaning to the ANSI codepage. It just doesn't matter. It woiuld work equally well with unicode from xp to 11, and the ANSI codepage just goes away.

> If busybox-w32 maintainers think this is a worthwhile feature,

It is a worthwhile feature, but at what cost?

And what is the value which this brings, and which the current Unicode using the manifest doesn't have?

I think the answer is only "it will work on older versions of windows".

I did put a lot of time to try to do just that. It is hard, and a lot of effort.

So if you want to help, sit down and see if you can address this issue.

Trying to convince others to do it because it would be nice for you or because you think it should be easy just doesn't cut it. No offence.

No one objects to have it. It would be great. But everyone does with their time what they want. I've put a lot of my time into this very thing, and decided to cut off my losses.

Now you should put your time and try.
