### ISSUE TITLE
`make` - automatic variables `$<` and `$*` works inside suffixes rules only

### ISSUE THREAD

**Issue by naksyl** [rmyorston/busybox-w32#407]
Test makefile:
```Makefile
all:
	@echo "Automatic variables from suffixes rule"
	@make -n AUTO=1 main.o
	@echo
	@echo "Automatic variables from regular rule"
	@make -n main.o

.c.o:
	$$< = "$<"
	$$? = "$?"
	$$@ = "$@"
	$$* = "$*"
	$$^ = "$^"

main.o: main.c common.h
ifndef AUTO
	$$< = "$<"
	$$? = "$?"
	$$@ = "$@"
	$$* = "$*"
	$$^ = "$^"
endif

main.c:
common.h:
```
Output:
```sh
$ make
Automatic variables from suffixes rule
$< = "main.c"
$? = "main.c common.h"
$@ = "main.o"
$* = "main"
$^ = "main.c common.h"

Automatic variables from regular rule
$< = ""
$? = "main.c common.h"
$@ = "main.o"
$* = ""
$^ = "main.c common.h"
```

**Comment by rmyorston** [comment]
The section on [Internal Macros](https://pubs.opengroup.org/onlinepubs/9699919799/utilities/make.html#tag_20_76_13_08) in POSIX states that `$@`, `$%` and `$?` "shall be evaluated for both target and inference rules". `$<` and `$*` are only required to be evaluated for inference rules.

busybox-w32 `make` is strictly enforcing the standard. It _could_ relax this behaviour, but it would be as a non-POSIX extension.

This issue is being tracked [upstream](https://github.com/rmyorston/pdpmake/issues/32).

**Comment by naksyl** [comment]
Thanks for the answer, i was not aware of that, so I shall stick to parse `$?` inside shell.

**Comment by rmyorston** [comment]
`make` in busybox-w32 now supports `$<` and `$*` in target rules as a non-POSIX extension.

It's in the lastest [prerelease binaries](https://frippery.org/files/busybox/prerelease) (PRE-5352 or above).

**Comment by rmyorston** [comment]
Support for `$<` and `$*` in target rules is available in the latest release, FRP-5398.
