### ISSUE TITLE
stderr redirection truncates output

### ISSUE THREAD

**Issue by vszakats** [rmyorston/busybox-w32#41]
```bash
#!/bin/sh

readonly logfile=test.log
rm -f "${logfile}"
echo '1' >> "${logfile}"
net start "(not_here)" 2>> "${logfile}"
echo '2' >> "${logfile}"
```

Notice the missing `1` line at the top of `test.log`, when run with either:
BusyBox v1.24.0-FRP-7-g316ecf2 (2015-05-27 15:40:02 BST) multi-call binary.
BusyBox v1.24.0-TIG-1784-gdb98881 (2015-04-22 21:47:46 BST) multi-call binary.
```
The service name is invalid.

More help is available by typing NET HELPMSG 2185.

2
```

`test.log` is correct when run with:
GNU bash, version 3.1.23(6)-release (i686-pc-msys)
```
1
The service name is invalid.

More help is available by typing NET HELPMSG 2185.

2
```

Redirection to stderr seems to truncate `test.log`.

**Comment by rmyorston** [comment]
This is a strange one.  It doesn't only affect stderr and it isn't truncating the log file, just writing to it with an offset of 0.  It only happens when an external command is run, not a BusyBox applet.

```
rm -f log
echo 1234567890 >>log
cmd /c echo hi >>log
echo 1234567890 >>log
```

results in the log file containing

```
hi
567890
1234567890
```

Somehow Windows is writing at the start of the file instead of the end.  I've fixed it by doing an explicit seek to the end of the file after it's opened.  I have no idea why that works.  It shouldn't be necessary:  the file is opened for append as it should be.

**Comment by vszakats** [comment]
Yes, offset 0 it is. (Just could not come up with a good example to demonstrate it that way.)
Many thanks for your quick fix, I confirm it working.
