### ISSUE TITLE
Prevent ~/.ash_history from being saved

### ISSUE THREAD

**Issue by neodyne** [rmyorston/busybox-w32#425]
As a way to [prevent ash history from being saved](https://unix.stackexchange.com/a/762506), for example when busybox.exe shell is run from a flash drive, could `busybox sh -l` and `busybox sh -s -c ". X:/path/to/.profile"` support:
```
~ $ cat ~/.profile
export HISTFILE=/dev/null # or =NUL ?
```
Currently the shell after sourcing `.profile` just closes, after typing any command.
`export HISTFILE=X:/valid/path/to/file` works, but obviously creates the file.

It seems the only other alternative would be something like `ln -s /dev/null ~/.ash_history`, so
`MKLINK.EXE "%USERPROFILE%\.ash_history" NUL:` , which requires elevation and is system-specific.
 
 (or to recompile with changed history-related config options)

**Comment by avih** [comment]
When running from sh:
```
HISTFILE=/dev/nul sh
```
then the 1st command results in sh exit with the following error:
```
sh: lseek(0, 2): Invalid seek
```
The only `lseek` I can see in `ash.c` is added at commit 6fb17897d620572290b1f604430c06c261145aad .

It's possible that this fails when trying to open/append to NUL HISTFILE, but I didn't try to confirm that.

It's not guaranteed to be the failed lseek, and code-wise that lseek seems to only be used from the ash-internal `redirect`, but I wouldn't guess that opening HISTFILE ends up using this function.

**Comment by rmyorston** [comment]
To prevent history from being recorded in a file set `HISTFILE` to an empty value in `.profile`:
```
export HISTFILE=
```
History will still be kept in memory, but not stored to a file. This also work in upstream BusyBox.

**Comment by rmyorston** [comment]
@avih I expect the `lseek()` you're seeing is the one in `libbb/lineedit.c`.

**Comment by neodyne** [comment]
> To prevent history from being recorded in a file set `HISTFILE` to an empty value in `.profile`:

This works, thank you.

**Comment by avih** [comment]
> @avih I expect the `lseek()` you're seeing is the one in `libbb/lineedit.c`.

I guess so, but on linux `HISTFILE=/dev/null busybox sh` seems to work.

Maybe `lseek(fd, 0, SEEK_END)` on windows shouldn't fail for NUL file?

**Comment by rmyorston** [comment]
The wrapper for `lseek()` was rather cautious and only accepted files on disk. Character devices seem to be OK too, so I've added support for them.

It's now possible to use `HISTFILE=/dev/null` or `HISTFILE=nul` to prevent history from being saved. At least, in [prerelease binaries](https://frippery.org/files/busybox/prerelease) from PRE-5378.

**Comment by avih** [comment]
> The wrapper for `lseek()` was rather cautious and only accepted files on disk. Character devices seem to be OK too, so I've added support for them.

Nice.

> In addition, the wrapper for open(2) now converts the Unix-style
> mode argument to Windows-style.

It's not immediately obvious to me why this change was added or how it's related to the lseek change.

Does this solve any known problem and/or modify the behavior of some known things?

Or is that a general compatibility enhancement which might become useful in the future or fix existing but unknown issues?

**Comment by rmyorston** [comment]
The change to the mode argument isn't necessary for the problem at hand. It's just something I noticed while investigating the matter.

There are plenty of calls to `open(2)` with `O_CREAT` and a mode argument in the upstream code. I haven't audited them to look for problems but it seemed reasonable to make the change as a precaution.

**Comment by rmyorston** [comment]
Actually, the definitions of the mode bits Windows wants are compatible with the user mode bits on Unix. So the code was probably OK even without the change.

**Comment by avih** [comment]
OK, first, I _think_ `mode` doesn't need an initialization to 0666 because it's always overwritten later as `mode = va_arg(args, int)`.

However, I'm not sure what value it would get if it's called with only 2 args. I _think_ it's undefined behavior?

C99 `va_arg`:
> If there is no actual next argument, ... the behavior is undefined

I might be missing something because otherwise I don't know how it can be distinguished in C whether there are 2 or 3 args, unlike `printf` for instance where the number of arguments is derived from the format string.

Next. Assuming we got past that hurdle and `mode` is either the 3rd argument or has a default value of 0666 (or maybe it should be changed to `_S_IREAD | _S_IWRITE`), then with the knowledge that the bits are compatible, it should suffice to do `pmode = mode & (_S_IREAD | _S_IWRITE)` (or just use that expression directly).

**Comment by avih** [comment]
> I'd been following the same thought process and got as far as: ...

LGTM.

What about the default mode value, possibly as 0, and simpler `pmode = mode & (_S_IREAD | _S_IWRITE)` ?

> We don't need to worry about `O_TMPFILE` because BusyBox doesn't use it and it isn't supported on Windows.

It's not posix, and I don't know if identical semantics as linux, but ms docs say:
> `_O_CREAT | _O_TEMPORARY`: Creates a file as temporary; the file is deleted when the last file descriptor is closed. The pmode argument is required when _O_CREAT is specified. To preserve legacy behavior for app-compatibility, other processes aren't prevented from deleting this file.

But on Windows it's apparently only supported with _O_CREAT anyway (I think?), so no need for special handling as far as pmode goes, except maybe adding _O_CREATE to flags if _O_TEMPORARY is set, though it's likely not worth adding unlees needed and someone reports a bug that a temp file remains someplace ;)

**Comment by rmyorston** [comment]
>`pmode = mode & (_S_IREAD | _S_IWRITE)`

This relies on the Unix and Windows mode bits being compatible. Although this is apparent from reading the include files it isn't guaranteed by the documentation.

`_O_TEMPORARY` isn't in Linux, so it'll never be used in BusyBox. It's safe to ignore it.

**Comment by avih** [comment]
There might be another issue.

Either `mingw_xopen` is unused and should be removed (I don't see what maps to it), or it is used, but I think buggy:

`xopen` (which takes exactly two args) is sometimes called with O_CREAT, then calls `xopen3(name, flags, 0666)`, but `mingw_xopen` takes two args and calls `mingw_open` with those two args, presumably even with O_CREAT, which can lead to incorrect pmode.

Regardless of the UB, presumably the possible bugs are either that the call is rejected because pmode is invalid, or the file is created as read-only instead of read-write (because in windows all files are readable, and the only imact pmode has is to decide whether it's also writable).

Regardless, the pmode docs are unclear to me:
> If a value other than some combination of _S_IREAD and _S_IWRITE is specified for pmode ... or if any value other than the allowed oflag values is specified, the function ... invokes the invalid parameter handler, as described in Parameter validation. If execution is allowed to continue, the function returns -1 and sets errno to EINVAL.

Because `_S_IREAD | _S_IWRITE` (`0x180`) is different than the combined "allowed oflag values" (which is definitely more than the two set bits of `0x180`, e.g. `_O_RDWR` is 2), so if the valus is e.g. 2, then it's not "some combination of _S_IREAD and _S_IWRITE", therefore it's invalid according to the 1st condition but it is an allowed oflag value, so it's not invalid not according to the second condition, so it's not obvious whether it's indeed invalid, and how it should be interpreted - because it only documents combinations of _S_IREAD and _S_IWRITE.

**Comment by rmyorston** [comment]
Calls to `mingw_xopen()` are constructed by the macro `MINGW_SPECIAL()`. All such calls are in relation to opening special devices (`/dev/zero` or `/dev/urandom`). These devices are assumed to exist (and even if they didn't there'd be no point in creating them). So calls to `mingw_xopen()` _don't_ include `O_CREAT`.

>the 1st condition refers to pmode, and the 2nd to oflag.

Yes, that was my understanding of the text.

**Comment by avih** [comment]
Thanks.

Is it waiting for anything else? currently master still has this UB with `open` with two args.

**Comment by rmyorston** [comment]
>Is it waiting for anything else?

Just for your final confirmation. Now shipped: [PRE-5381](https://frippery.org/files/busybox/prerelease) or above.

**Comment by avih** [comment]
I didn't think there were open things left, and didn't realize you're waiting for me. Thanks for the update.
