### ISSUE TITLE
Prompt is sent to stdout

### ISSUE THREAD

**Issue by ale5000-git** [rmyorston/busybox-w32#442]
When running bash like this:
`bash 1>&-`
you still see the prompt because it is sent to stderr.

Instead with
`busybox ash 1>&-`
you don't see the prompt.

**Comment by rmyorston** [comment]
>Prompt is sent to stdout

No, that's not it. Since upstream commit fd47f056765aed515f4c71118813f07be1402bee prompts are sent to `stderr`. Thus the current release, FRP-5398, _does_ write prompts to `stderr`.

The cause is different: line editing and prompts are only enabled if the shell is interactive. And a shell is only considered to be interactive if both `stdin` and `stdout` are connected to a terminal.

This isn't unique to the shell in busybox-w32: the same behaviour is present in upstream BusyBox and `dash`. So this isn't something I'd wish to change just for the Windows port.

A workaround is to force the shell to be interactive: `busybox ash -i 1>&-`

**Comment by ale5000-git** [comment]
Ok, thanks.
