### ISSUE TITLE
awk integer limits

### ISSUE THREAD

**Issue by ale5000-git** [rmyorston/busybox-w32#453]
In 32-bit busybox the max limit of signed decimal works correctly:
```
awk -v n="2147483647" -- 'BEGIN { printf "%d\n", n }'
```
but instead the one of unsigned decimal return an incorrect number:
```
awk -v n="4294967295" -- 'BEGIN { printf "%u\n", n }'
```

Is it possible to fix this issue and also is it possible to use 64-bit integers on the 32-bit build also for printf inside awk?

**Note:** printf outside awk, shell aritmetic and the test builtin all support 64-bit integers on the 32-bit build of busybox.

**Comment by rmyorston** [comment]
Numbers in awk are represented as `double`. When printed as integers they're cast to `int`. A workaround to see the full precision is to use a floating point format.

The same problem is present in the upstream 32-bit build. There's a [bug report](https://bugs.busybox.net/show_bug.cgi?id=15041) with a patch, but no action as yet. (Probably in part because it removes a TODO explaining some problems without actually addressing them.)

**Comment by ale5000-git** [comment]
Why this can work?
```
$ awk -- 'BEGIN { printf "%u\n", "-1" }'
4294967295
```
```
An this not?
$ awk -- 'BEGIN { printf "%u\n", "4294967295" }'
2147483648
```

When %u is used why it cannot be cast to `unsigned long`?

**Comment by rmyorston** [comment]
>When %u is used why it cannot be cast to unsigned long?

It could be (though octal and hex formats are also unsigned and should probably be given the same treatment). But this is an upstream problem and I don't want to carry a local fix.

**Comment by ale5000-git** [comment]
Thanks, I will clode the ticket for now and report it upstream.

**Comment by ale5000-git** [comment]
I have written a comment about this issue here: https://bugs.busybox.net/show_bug.cgi?id=15041
