### ISSUE TITLE
Error out on unknown long options

### ISSUE THREAD

**Issue by ale5000-git** [rmyorston/busybox-w32#457]
Scripts may want to check the shell version by using:
`$0 --version`
or
`$SHELL --version`

BusyBox doesn't support it but it is an upstream issue.

Now the biggest problem is that instead of error out it open an interactive shell and this freeze the script.
Could you please error out on `--version`? (with a clear message: `ash: unrecognized option '--version'`)

Maybe also error out on `--init-file` since having the command illusorily working without being supported is annoying.

**Comment by avih** [comment]
> Scripts may want to check the shell version by using:
> `$0 --version`

It may want to do many things, but this specific one would not be wise, because login shell typically has `-` prepended, e.g. in a bash login shell $0 is `-bash`, and you can't run it because there's no `-bash` in $PATH.

> or
> `$SHELL --version`

Again, not wise, because that's not standard.

Also, shells gain features and bugs over the years, so the fact that you think you know what the shell is doesn't guarantee that the feature you want to use would work.

There's no obvious method to identify busybox-ash or dash or freebsd or netbsd (a)sh, and same for many other shells.

You can sort of identify bash using $BASH_VERSION, and zsh using $ZSH_VERSION, but if you really want bash then use a `#!/bin/bash` shebang instead of running as a standard shell and wanting to use non standard features.

If you want to use non standard feature which you're not sure if they exist, then your best course of action is to test the specific features in your script before you try to use them.

The solution is not to add features which makes it easier to identify the shell, because this is a rabbit hole that no one wants to get into.

**Comment by ale5000-git** [comment]
Actually I only use it to display shell info and not for the code itself.
I haven't asked any new option but just to display error for unsupported options.

Also I code script to work on all shell and all OS in the world (at least the idea is this).

**Comment by rmyorston** [comment]
OK, I have good news and I have bad news.

The good news is that busybox-w32 `ash` now rejects all unknown long options. Not just `--version` or `--init-file`, _all_ of them.

The bad news is that the error message is not at all clear: it says `sh: illegal option --`. That's just the way it is. Other `ash` variants are no more informative.

The culprit was commit 64f70cc755b89c29aa03dc9555a1df37de17bcfd (from 2002) which added support for the `--login` option. As a side effect it caused the shell to silently accept all _other_ long options.

There are, of course, [prerelease binaries](https://frippery.org/files/busybox/prerelease) (PRE-5468 or above). If they work to everyone's satisfaction (or, at least, if nobody grumbles _too_ much) I'll submit an upstream patch.

**Comment by ale5000-git** [comment]
It seems to work fine now, thanks.

**Comment by rmyorston** [comment]
The patch has been submitted upstream.

**Comment by rmyorston** [comment]
Upstream have taken my patch. They've also added a clear error message: 
```sh
~ $ sh --version
sh: bad option '--version'
~ $
```
Try the [latest prerelease](https://frippery.org/files/busybox/prerelease) (PRE-5484 or above).

**Comment by ale5000-git** [comment]
It works fine, thanks.
