### ISSUE TITLE
date applete %z %Z formating doesn't conform to IEEE Std 1003.1-2001

### ISSUE THREAD

**Issue by dgtlrift** [rmyorston/busybox-w32#46]
%z
    Replaced by the offset from UTC in the ISO 8601:2000 standard format ( +hhmm or -hhmm ), or by no characters if no timezone is determinable. For example, "-0430" means 4 hours 30 minutes behind UTC (west of Greenwich). [CX] [Option Start]  If tm_isdst is zero, the standard time offset is used. If tm_isdst is greater than zero, the daylight savings time offset is used. If tm_isdst is negative, no characters are returned. [Option End] [ tm_isdst]
%Z
    Replaced by the timezone name or abbreviation, or by no bytes if no timezone information exists. [ tm_isdst]

I believe the core issue here is a short-coming in the windows API described in https://msdn.microsoft.com/en-us/library/fe06s4ak.aspx - this issue is low priority, but should be documented.

**Comment by rmyorston** [comment]
I've modified my front end to the Windows `strftime` function so that `%z` is replaced by the timezone offset.  It's possible some corner cases aren't handled properly.

A workaround for `%Z` is to set the `TZ` environment variable.  Windows will then use the timezone names from the environment variable in preference to its own names.

**Comment by dgtlrift** [comment]
Good work around... works enough for me... would be nice if MS could just actually implement the standard, but this works for me.
