### ISSUE TITLE
Question about backslash

### ISSUE THREAD

**Issue by ale5000-git** [rmyorston/busybox-w32#462]
Inside single quotes the backslash should be treated literally but why this work:
`ls -1 -d -- '.\my_dir/'*`
but this does NOT work?
`ls -1 -d -- '.\my_dir\'*`

**Comment by rmyorston** [comment]
The shell globbing code follows POSIX conventions and only looks for '/' as a directory separator. Backslashes are accepted in parts of the path that don't have any patterns.

The same is true of tab completion.

**Comment by ale5000-git** [comment]
Ok. thanks.

**Comment by avih** [comment]
> The shell globbing code follows POSIX conventions and only looks for '/' as a directory separator. Backslashes are accepted in parts of the path that don't have any patterns.
> 
> The same is true of tab completion.

Unclear to me whether you think the w32 version should accept `\` in this case (it might still not be worth fixing, e.g. if it's too hard, but at least specify what it _should_ do).

FWIW, I think it should, because globbing is very closely tied to path interpretation, and if path interprets `\` as separator on windows, then I don't think it should prevent globbing (or tab completion).

**Comment by ale5000-git** [comment]
If busybox got started with `-X`, then using an env var to do the globbing will break scripts.

**Comment by avih** [comment]
> closed this as not planned

Why did you close it as not-planned? I don't see any hint for that in the reply.

It only explains why the bug happens. It doesn't say that it's not a bug or that it's not planned.

I think you should reopen it.

**Comment by rmyorston** [comment]
The first responsibility of the shell in busybox-w32 is to implement correct handling of backslash as an escape character.

This makes the use of backslash as a directory separator in Windows problematic, both for the user and the implementation.

I don't at present have any plan to make changes in this area.

**Comment by avih** [comment]
> The first responsibility of the shell in busybox-w32 is to implement correct handling of backslash as an escape character.

Sure. Agreed.

> This makes the use of backslash as a directory separator in Windows problematic, both for the user and the implementation.

I don't yet see why, or how it's related to the escape comment above.

in bb-w32 `$PATH` rightly allows backslash in paths, execution rightly also allows it, files in unix are allowed to contain literal backslashes, and, if quoted correctly, should not be interpreted as an escape while globbing.

Shouldn't fixing it be as simple as checking also `\` where the glob implementation checks `/`? (famous last words)

Alternatively, maybe globbing should first convert backslashes to slashes? (and if one wants to be cute, also restore converted backslashes at the result, but it's probably not worth the effort, and it can become complex quickly)

**Comment by avih** [comment]
Here's another idea for this changeset.

To recap, two main subjects are addressed here:
- There's an issue with "waiting for all scripts to finish init". Currently it uses 0-timeout - which doesn't wait correctly for all scripts. The suggested solution was to add an event `initialized`, which would it fix it perfectly, but arguably is an overkill to fix this specific non-critical issue, and also we can't seem to agree on whether it should be public or undocumented.
- Now that there's a central facility to calculate string terminal width, it's better to use it instead of the internal `terminal_ellipsis`. The approach which this patchset takes is to use the mpv logging facility instead of `io.write`, and enable this truncation at the log output.

And as a result of using the log, some additional changes were added to ensure that it can print to the output without clearing the screen on exit, such as the flush command, and some use of timeouts to workaround internal log output timing (or some such - I didn't get that part fully).

Now, this is a suggestion to make this patchset much smaller:
1. Use 250 ms timeout instead of 0 (and instead of the event). It's not very nice, and certainly less accurate than the `initialized` event, but it would likely cover the vast vast majority of use cases of scripts which add bindings during their init phase. Or maybe some other value, or some other trigger (i.e. not timeout) which we can use without additional infrastructure and which is still likely to cover binding-at-init. It's OK if we don't get 100% coverage, but preferably we get good coverage.
2. Add an mpv command `truncate_text` or `text_ellipsis` ot some such which can do the truncation better than the internal `terminal_ellipsis` (because it has wcwidth), then simply use that instead of the logging - while still using `io.write`. Not nice, but also not less-nice than before, but with better calculation of the truncation.

And in the future, we can still replace `io.write` with something else once the log output timing is less fiddly.

I also don't think this PR is bad. The only issue is the fiddly timing of the output/flush, but I trust that it works well, so I don't have anything against it. I'm just trying to move it forward with maybe something simpler.
