### ISSUE TITLE
find applet with -perm option

### ISSUE THREAD

**Issue by dgtlrift** [rmyorston/busybox-w32#47]
Would be useful if windows permissions could be matched in find and searchable according to how chmod sets them.

As far as finds core main-line functionality, it would also be nice if the main-line busybox find applet also supported the -writable -readable and -executable flag even if they redundant to -perm, but I realize that may be more of a linux thing and less of a posix standard.

**Comment by rmyorston** [comment]
It's certainly possible to build busybox-w32 with the -perm option enabled.  I've never done so because I didn't think it would be terribly useful.  Permissions in busybox-w32 are a sort of collision between Windows and Unix concepts.  Having said that, they're better than they used to be so I'll enable -perm in the default build.  I won't make new binaries just for that, though.  I'll let you know when I do.

The additional permissions flags appear to be a GNU extension.  This isn't really the place to ask for enhancements to upstream BusyBox.

**Comment by dgtlrift** [comment]
Okay - tnx - I didn't go too overboard, but I've been pulling, modding, and building from git.  What forum should I use for a push request if there's something I've done that I think may be of value?

**Comment by rmyorston** [comment]
Upstream development happens on the [BusyBox mailing list] (http://busybox.net/lists.html), though it's all done with patches rather than pull requests.
