### ISSUE TITLE
Up button overwrite the previous printed text

### ISSUE THREAD

**Issue by ale5000-git** [rmyorston/busybox-w32#474]
First print something and end-up like this:
```
~ $ printf '123'
123~ $
```

Then press up button to retrieve the previous command; it will overwrite the `123`.
I have tried on the online Bash and `123` is kept.

**Comment by rmyorston** [comment]
It's an upstream issue. Previously discussed in issue #404.

**Comment by ale5000-git** [comment]
Thanks, I have reported it here: https://bugs.busybox.net/show_bug.cgi?id=16243

**Comment by avih** [comment]
@ale5000-git you surely know that busybox-w32 is not supposed to follow bash behavior.

It's supposed to follow upstream busybox, and while many posix and bash behaviors work in busybox-w32, the first reference and comparison should always be to upstream busybox.

Compatison to bash as well can be useful in some cases, but not before comparing (and reporting) how it behaves in upstream busybox.

You don't need @rmyorston to tell you that it's the same in upstream busybox, because you should test it yourself first.

**Comment by avih** [comment]
Also, the gist of the issue is that when busybox redraws the prompt+input (specifically the last prompt line if it's multi-line), which happens sometimes during editing, then it assumes that the prompt begins at the first terminal column, because it usually does.

When you print something without final newline, then the prompt is then printed at the not-begining of the line, which results in symptoms like you observed when the prompt+input are redrawn.

It's surely fixable, but the prompt code is complex and delicate and it's not guaranteed that someone would find the time and energy to handle that, because it's an unusual case and unharmful behavior.

If you want to ensure that (the last line of) the prompt always begins at the first column, then simply ensure that your PS1 starts with `\n`.

**Comment by ale5000-git** [comment]
@avih
Bash on Linux can be tested under Windows with a browser (there are a lot of sites that allow this).
Instead it isn't the same with BusyBox.
There is one Live BusyBox but it is very old so not worth comparing.

I don't want \n in PS1 because it is a useless newline everytime.

It is fine even if it takes time but it is important to keep track and never give up.
As example one minor bug of Thunderbird was fixed after 18 years.

**Comment by avih** [comment]
Yes, I don't know if recent busybox is available to test in a browser, and absolute latest upstrean busybox (master) surely isn't, but that is the reference which busybox-w32 follows, and therefore the first point of comparison when things look broken in busybox-w32.

You can run a linux VM (e.g. live CD/DVD of some linux distro you prefer), and build upstream busuybox master yourself.

The point is that even if it's hard to find upstream busybox, it's still the reference to busybox-w32, and bash isn't.

**Comment by avih** [comment]
@ale5000-git I think the simplest way to try a recent pre-built busybox (though not necessarily master) is to boot Alpine linux in a VM, and busybox is already installed and is the default shell and utilities.

Download the latest "VIRTUAL" ISO image for x86 or x86_64 from here https://alpinelinux.org/downloads/ .

That's a relatively tiny file - the x86 ISO image is less than 50M for fully bootable alpine linux with recent busybox.

You can boot it in virtual box - which is also free and open source, login as "root" (no password), and start playing with busybox right away.

That's it. It's that simple.

But if you also want to build busybox master, then it's also relatively quick in this same virtual machine. Type these at the shell prompt:

```sh
# setup alpine to allow installing additional packages
setup-interfaces -ar  # start network with dhcp
setup-apkrepos -1c    # enable packages, 1st CDN, plus community repo

# add some development tools
apk add git make gcc musl-dev linux-headers  # maybe also vim or nano

# get latest busybox source code
git clone https://git.busybox.net/busybox
cd busybox

# in the future, if it's already cloned, "git pull" will update it

# build busybox master
make defconfig -j8
make -j8

# ./busybox should now be usable.
```

And obviously you can also install it to the hard disk (in the VM or on real hardware) if you don't want to repeat all the development setup commands with the live CD every time you boot.

But if you only want to test recent busybox, and don't want to build busybox master, then the live CD without installation is perfectly enough and quick and easy to run.

Check the Alpine linux docs for more info.

**Comment by ale5000-git** [comment]
@avih
Probably the less resource hungry way (regarding CPU and RAM) is to use Windows Subsystem for Linux (WSL) under Windows 10.
I just need to find how to compile BusyBox under WSL (in case there is any difference); I haven't tried yet.

**Comment by avih** [comment]
Sure. Whatever makes you happy, as long as you have a way to compare with upstream busybox yourself.
