### ISSUE TITLE
Treat `:path/to/file` as a relative path to the current root

### ISSUE THREAD

**Issue by smalltalkman** [rmyorston/busybox-w32#479]
A few thoughts while looking at the documentation, recorded here...

```
Thirdly, there's a path that has no root specifier and starts with a single slash (e.g. /path/to/file). This is relative to the current root. On Unix it would be an absolute path.
```

As mentioned above: On Unix `/path/to/file` would be an absolute path.

Is it possible to keep the meaning of `/path/to/file` consistent with unix? And treat `:path/to/file` as a path relative to the current root?

Perhaps it is possible to interpret `/` as BB_SYSTEMROOT (which defaults to SYSTEMDRIVE). And interpret `:` as the current root.

**Comment by rmyorston** [comment]
>Is it possible to keep the meaning of /path/to/file consistent with unix?

Only, I think, at the expense of it _not_ being compatible with Windows.

busybox-w32 is a WIN32 application which runs on Windows and its applets are often used from the command prompt. Both for reasons of compatibility and ease of implementation I think it best to follow the Windows conventions for paths.

>Perhaps it is possible to interpret / as BB_SYSTEMROOT (which defaults to SYSTEMDRIVE).

That interpretation _is_ made in few cases where upstream BusyBox has a hard-coded Unix-style path: `/etc/profile` in the shell, for example. I don't think it's appropriate to make it as a general rule.

>And interpret : as the current root.

That interpretation would be unique to busybox-w32. It would be meaningless to other Windows applications and to Cygwin/MSYS2 applications. It's bad enough that the latter have their own `/c/path/to/file` convention; I'd prefer not to add another.

**Comment by avih** [comment]
> Is it possible to keep the meaning of `/path/to/file` consistent with unix?

But there's no single root on windows.

Each drive has its own root, and if you don't specify a drive, then `/foo/bar` is the root of the current drive.

You should also keep in mind that even if bb-w32 decides that `/foo/bar` is always `C:/foo/bar` (even when CWD is at some other drive), then 3rd party win32 apps don't know that, and they (or rather windows) will consider this string at the root of the current drive.

And if you think that in such case bb-w32 should modify the arguments that it passes to external apps, then think again, because this is a very slippery slope. How would bb-w32 even know that a string argument is intended to be treated as a path by an external application, and not some string to use in other ways? (print it, whatever).

You could use UNC, with a single root for all drives (e.g. `'//localhost/c$/path/in/drive/c'`), but not all application behave nicely when CWD is UNC, and you can only hope that they preserve the leading double-slash, because if then don't, then it becomes at the current drive.

In cygwin, for instance (the base for msys2 - which is used by git-for-windows), they do have a unix root, but root is not any specific windows path which you know. Instead, they put the windows drives at `/cygdrive/c/whatever` they never convert arguments when passing to 3rd party applications. So the user is responsible to convert the arguments, typically using `cygpath` when running non-cygwin applications.

msys2, on the other hand, goes out of its way to automate the unix msys2 (cygwin) path into windows path in arguments to external application. It works usually, except when it doesn't, and it involves a lot of guesswork.

**Comment by smalltalkman** [comment]
Thanks for the explanation. After looking at [file-path-formats](https://learn.microsoft.com/en-us/dotnet/standard/io/file-path-formats) and [windows-file-paths](https://www.fileside.app/blog/2023-03-17_windows-file-paths/), it is indeed difficult to use the unix root directory concept in windows. I hope that in the future a mechanism can be implemented to leave the choice of the root directory to the user.

**Comment by ale5000-git** [comment]
@smalltalkman
All problems can be easily avoided at script side by resolving every path with `realpath`.
