### ISSUE TITLE
Very slow del/backspace in sh when the console has big buffer hight

### ISSUE THREAD

**Issue by avih** [rmyorston/busybox-w32#55]
- At the Windows console properties, set layout -> screen buffer size -> height = 9999 (the maximum)
- run the shell using `busybox sh -l`
- At the shell prompt, type few characters
- Try to delete the chars by holding down the backspace key

This responds very very slowly. The DEL key is also very slow.
If I run vi from the same slow shell, then backspace works fast, but then I exit vi back to the shell - slow again.

If I change the screen buffer height to something smaller, then both backspace and del are fast as they should.

**Comment by rmyorston** [comment]
I tried this in Windows 8.1 and 10.  With a large buffer height the response to backspace was certainly slower than the keyboard autorepeat rate, but not unacceptably so.  I wouldn't even describe it as 'very slow' much less 'very very slow'.

**Comment by avih** [comment]
I agree that "slow" and "very slow" were not a good descriptions.

On a windows 8.1 system with i7-4500u, with the system set to maximum repeat rate at the control panel (which is ~30-40 repeats/sec), when the buffer height is set to 9999, busybox sh backspace (or del) repeat rate becomes between about 3/sec to 1/sec.

I didn't figure out yet what affects is to end up as 3/sec or 1/sec.

That's a subjective thing, but IMO even as 3/sec it makes the shell uncomfortable enough to use except if one has to. And 1/sec is very uncomfortable. IMHO :)

**Comment by rmyorston** [comment]
The delay was caused by clearing to the end of the buffer every time a character was deleted. I've changed this so it only clears to the end of the current line. I think this should be OK but it would be good if you could check that this works for you.

I've put a new binary on my website (FRP-403-ga89270b).

**Comment by avih** [comment]
Confirmed that del/backspace are fast now. Thanks.

However, it seems that the same symptom also happens with history navigation (up/down) and search (ctrl-r).

I didn't check them earlier, and I don't know if there are more cases beyond those.

**Comment by rmyorston** [comment]
Most of the other cases where the whole screen is cleared are handled by the `redraw()` function. I've modified this so it only clears to end of line. The one exception is the ^L 'clear screen' keybinding.

I've built a new binary (FRP-404-gca94737) but since this change is more dangerous I haven't made it the default on my website yet. It can be downloaded as https://frippery.org/files/busybox/busybox-w32-FRP-404-gca94737.exe

**Comment by avih** [comment]
Didn't check this yet (I assume it works well), but I think I understand where all these come from.

On "normal" terminals (tested `gnome-terminal`, `putty` and `mintty`), the scrollback buffer doesn't seem to be part of the "screen", and `ctrl-l` clears only the "screen" part but leaves the backbuffer unmodified.

On the windows implementation it seems that these slow operations consider the entire scrollback buffer of the window console as the screen (and indeed `ctrl-l` clears the entire scrollback buffer), therefore taking much longer to update it if it's big.

For some reason, `vi` works well. Maybe because it emulates alt-screen and doesn't consider the scrollback buffer at all.

The fix for all of those combined might be in the handling of `ESC[J` (`win32/winansi.c` ?).

I'd try to hack it myself and I do have a cross build environment (MXE on Ubuntu FWIW), but I'm getting lost with all the options at `menuconfig`. Care to share your config file such that I'd use it as a starting point?

**Comment by rmyorston** [comment]
Indeed, the issue is that the interpretation of ANSI escapes in busybox-w32 doesn't conform to how terminals actually work. Cursor positions in ANSI escapes are relative to the screen while in the `CONSOLE_SCREEN_BUFFER_INFO` structure they're relative to the buffer. There's a separate structure element (`srWindow`) that says which part of the buffer in currently being displayed.

To keep things simple the code in `winansi.c` equated ANSI cursor positions with the position relative to the buffer. In the branch `ansi` I've reverted the last two changes I made and have modified `winansi.c` to use screen-relative cursor positions. This has several advantages:

* most of the buffer is preserved when the screen is cleared, only the lines actually being displayed are lost
* `erase_till_end_of_screen` only needs to loop through the lines being displayed, not the entire buffer
* the changes are limited to the `win32` portability layer

I've put a temporary build of the `ansi` branch on my website as https://frippery.org/files/busybox/busybox_ansi.exe

There are default configurations for 32- and 64-bit mingw in the `configs` directory. Rather than struggle with `make menuconfig` you can get sane defaults by running `make mingw32_defconfig` or `make mingw64_defconfig` as appropriate.

**Comment by avih** [comment]
`busybox_ansi.exe` is better indeed. Thanks!

vi and less now don't delete the entire backbuffer (and still seems to work as expected), which is nice.

I noticed one proper issue after some experiments: the bottom line of the screen is not cleared on ctrl-l (regardless if the cursor is at the bottom or not).

And possibly related (and/or addressable in the same changes) to improve usability:
- if the screen is scrolled back, and then using ctrl-l, it clears the current "view" and brings the cursor to it (leaving stuff below the current view). This seems to be different than other terminals where ctrl-l first moves the "view" to the bottom/where the cursor is, and then does its thing (I'm intentionally vague since I didn't try to analyze what it does exactly).
- By default, most terminals move the "view" to the bottom/where the cursor is on any key press.

I realize that busybox is not about vt100 emulation on the windows console, but since it sort of does it anyway, I thought I'd mention it ;)

**Comment by rmyorston** [comment]
OK, not clearing the bottom line just means I stopped the loop in `erase_till_end_of_screen` one iteration too soon.

I had considered what would happen if the user scrolled back and cleared the screen, but I tested it with the `clear` command rather than ^L. The former repositions the display to show the command being typed while the latter doesn't. I've added `ESC[0A` (move cursor up by zero lines) to the code that handles ^L to get the same effect.

There's a [busybox_ansi2.exe](https://frippery.org/files/busybox/busybox_ansi2.exe) with these changes.

Hmm, viewports for `vi` and `less`. If the user scrolls the display while using one of these the results quickly get very confusing. Unless there's some way to prevent that it may be necessary to go back to having these commands clear all of the buffer.

**Comment by avih** [comment]
> ... you can get sane defaults by running make mingw32_defconfig ..

That worked :)

Here's a small patch on top of your "ansi2" patch:
- Move the viewport to the cursor on any lineedit keypress if stdin and stdout are a tty (instead of only for ctrl-l).
- `erase_till_end_of_screen` and and `move_cursor` do the same regardless of lineedit (since they refer to screen space and not buffer, and may be called not only from lineedit).
- Unrelated minor simplification of `erase_till_end_of_screen`.

I also experimented with this inside `lineedit_read_key(...)` and also at `win32/termios.c::read_key(...)` as a more generic console behavior of "scroll to the bottom on any key", and both work fine as far as I can tell, but eventually decided against it since I wasn't sure what side effects it might have at these relatively lower level functions.

(sorry, apparently GH doesn't like diff attachments...)
```diff
diff --git a/libbb/lineedit.c b/libbb/lineedit.c
index 37c106b..0a912b1 100644
--- a/libbb/lineedit.c
+++ b/libbb/lineedit.c
@@ -2440,6 +2440,15 @@ int FAST_FUNC read_line_input(line_input_t *st, const char *prompt, char *comman
 
 		fflush_all();
 		ic = ic_raw = lineedit_read_key(read_key_buffer, timeout);
+#if ENABLE_PLATFORM_MINGW32
+		/* typically it's the console's task to scroll to the bottom on key
+		 * press, but the windows console doesn't, so do it ourselves by
+		 * "touching" the cursor position (to which the console responds by
+		 * moving the viewport to the include cursor) */
+		if (isatty(fileno(stdin)) && isatty(fileno(stdout)))
+			printf(ESC"[0A");
+#endif
+
 
 #if ENABLE_FEATURE_REVERSE_SEARCH
  again:
@@ -2510,9 +2519,6 @@ int FAST_FUNC read_line_input(line_input_t *st, const char *prompt, char *comman
 		case CTRL('L'):
 		vi_case(CTRL('L')|VI_CMDMODE_BIT:)
 			/* Control-l -- clear screen */
-#if ENABLE_PLATFORM_MINGW32
-			printf(ESC"[0A"); /* move to current cursor postion */
-#endif
 			printf(ESC"[H"); /* cursor to top,left */
 			redraw(0, command_len - cursor);
 			break;
diff --git a/win32/winansi.c b/win32/winansi.c
index 78d5d5f..5f814d0 100644
--- a/win32/winansi.c
+++ b/win32/winansi.c
@@ -89,6 +89,8 @@ static void set_console_attr(void)
 	SetConsoleTextAttribute(console, attributes);
 }
 
+static void viewport_to_cursor(void);
+
 static void erase_in_line(void)
 {
 	CONSOLE_SCREEN_BUFFER_INFO sbi;
@@ -109,28 +111,19 @@ static void erase_in_line(void)
 static void erase_till_end_of_screen(void)
 {
 	CONSOLE_SCREEN_BUFFER_INFO sbi;
-	COORD pos;
-	DWORD dummy;
+	DWORD dummy, len;
 
 	if (!console)
 		return;
 
+	viewport_to_cursor();
 	GetConsoleScreenBufferInfo(console, &sbi);
-	FillConsoleOutputCharacterA(console, ' ',
-		sbi.dwSize.X - sbi.dwCursorPosition.X, sbi.dwCursorPosition,
-		&dummy);
-	FillConsoleOutputAttribute(console, plain_attr,
-		sbi.dwSize.X - sbi.dwCursorPosition.X, sbi.dwCursorPosition,
-		&dummy);
 
-	pos.X = 0;
-	for (pos.Y = sbi.dwCursorPosition.Y+1; pos.Y <= sbi.srWindow.Bottom;
-			pos.Y++) {
-		FillConsoleOutputCharacterA(console, ' ', sbi.dwSize.X,
-					    pos, &dummy);
-		FillConsoleOutputAttribute(console, plain_attr, sbi.dwSize.X,
-					    pos, &dummy);
-	}
+	len = sbi.dwSize.X - sbi.dwCursorPosition.X +
+	      sbi.dwSize.X * (sbi.srWindow.Bottom - sbi.dwCursorPosition.Y);
+
+	FillConsoleOutputCharacterA(console, ' ', len, sbi.dwCursorPosition, &dummy);
+	FillConsoleOutputAttribute(console, plain_attr, len, sbi.dwCursorPosition, &dummy);
 }
 
 static void move_cursor_row(int n)
@@ -165,12 +158,21 @@ static void move_cursor(int x, int y)
 	if (!console)
 		return;
 
+	viewport_to_cursor();
 	GetConsoleScreenBufferInfo(console, &sbi);
 	pos.X = sbi.srWindow.Left + x;
 	pos.Y = sbi.srWindow.Top + y;
 	SetConsoleCursorPosition(console, pos);
 }
 
+static void viewport_to_cursor(void)
+{
+	/* SetConsoleCursorPosition also moves the viewport to include the cursor.
+	 * Useful to execute before actions which address absolute screen space.
+	 */
+	move_cursor_row(0);
+}
+
 static const char *set_attr(const char *str)
 {
 	const char *func;
```

**Comment by rmyorston** [comment]
Thanks for the patch. I've taken parts of it.

* Since the code runs on every keypress I've implemented viewport scrolling by exposing `move_cursor_row`. This avoids going through the ANSI emulation cruft. I agree that `read_line_input` is the best place for the test.
* The simplification of `erase_till_end_of_screen` is nice.

I don't think scrolling to the cursor is appropriate in `erase_till_end_of_screen`, or necessary in `move_cursor`. But I'm still pondering what to do about `vi` and `less` and may want to make other changes in these areas.

**Comment by avih** [comment]
> I don't think scrolling to the cursor is appropriate in erase_till_end_of_screen

Obviously it's meaningless if the viewport doesn't include the cursor.

Between the options of bringing the cursor to the current viewport, or moving the viewport to include the cursor, I think the latter is more inline with other terminals, since the cursor is always at the "screen" part (at the "bottom" of the scroll buffer), but if you scroll back and then clear the screen, you end up clearing a rectangle at the backbuffer instead of the "screen" at the bottom.

But sure, up to you.

**Comment by rmyorston** [comment]
> but if you scroll back and then clear the screen

When would this be a problem?  With the change in `lineedit.c` using `clear` or ^L will move the viewport to the cursor.

I've been unable to get `vi` and `less` working to my satisfaction. In a proper terminal it isn't possible to scroll through the buffer when using `vi`, with the Windows console it was. If I did that (possibly accidentally, by using the mouse wheel to scroll through the file being edited) getting back to the section of the screen where the editing was happening was tedious. Hitting ^L to redraw the editor was easy, but then the editor was using a screen in the middle of the buffer.  Quitting the editor then left lines of buffer after the command prompt. It was all very confusing.

In my latest commit I've reverted to the old behaviour for `vi` and `less`: they move the cursor to the top of the buffer and clear all of it.  [busybox_ansi3.exe](https://frippery.org/files/busybox/busybox_ansi3.exe)

**Comment by avih** [comment]
> When would this be a problem? With the change in lineedit.c using clear or ^L will move the viewport to the cursor.

True, but not all clears happen from lineedit. e.g. some ascii animation etc.

But whatever you end up with, most likely would have some compromises, but regardless will be better than where we started ;) So take your pick.

**Comment by rmyorston** [comment]
Right, I've rebased the latest changes onto master to make it look as though I knew what I was doing ;-) and I've updated the binary on my website. The temporary binaries have gone.

Thanks for your help with this.

**Comment by avih** [comment]
Thanks!
