### ISSUE TITLE
PATCH: Add link support for socketpair()

### ISSUE THREAD

**Issue by dgtlrift** [rmyorston/busybox-w32#72]
After the last git pull, I ran into an issue with including wget as part of the build where it was referencing socketpair and failing to link... to work around it, I added an empty implementation of socketpair().
[socketpair.patch.txt](https://github.com/rmyorston/busybox-w32/files/767250/socketpair.patch.txt)

**Comment by rmyorston** [comment]
Support for HTTPS in ```wget``` has changed.  To avoid including ```socketpair``` it's necessary to turn off the configuration option 'Support HTTPS using internal TLS code'.  This code won't work as it stands because it requires a fork.  The 'internal code' referred to is the new ```ssl_client``` applet.

The default mingw configurations have ```CONFIG_FEATURE_WGET_HTTPS``` unset to avoid the need for ```socketpair``` and ```CONFIG_SSL_CLIENT``` unset because it's only needed for HTTPS support.
