### ISSUE TITLE
timeout applet

### ISSUE THREAD

**Issue by ale5000-git** [rmyorston/busybox-w32#79]
Please include timeout applet.

**Comment by rmyorston** [comment]
I've implemented something vaguely like ```timeout```.  The code is an almost total rewrite using WIN32 rather than POSIX. There are some serious limitations:

- the only signal recognised is ```TERM```
- the child process is terminated with ```TerminateProcess```, which may be untidy
- children of the child process aren't terminated

I've put a temporary test binary on my website:  ```busybox_timeout.exe```.

**Comment by ale5000-git** [comment]
I get it from [here](https://frippery.org/files/busybox/busybox_timeout.exe).

Thanks, it works perfectly for my needs.
Is it possible to include it inside busybox_safe.exe?

**Comment by rmyorston** [comment]
Since it works for you I've added ```timeout``` to the latest build, FRP-1601.  Binaries for all variants, including busybox_safe.exe, are available on my website now.  The temporary test binary has been removed.
