### ISSUE TITLE
unzip regression fix

### ISSUE THREAD

**Issue by ale5000-git** [rmyorston/busybox-w32#80]
Hi,
when you have time can you please also include the fix for the unzip regression [here](https://git.busybox.net/busybox/commit/?h=1_27_stable&id=4989d05174efd267d2fd85dc2e7f7beaafb8ab37)?

**Comment by rmyorston** [comment]
I'm confused.

The fix was included in upstream master on 25th July and was picked up when I merged with upstream on 27th July. So the fix is in the code.

The last binaries I built were on 24th July, so they don't include the fix. But I only provide binaries for little-endian platforms which aren't affected by the bug. So there's no need to update the binaries.

Unless I'm missing something I don't think any action is required.

**Comment by ale5000-git** [comment]
Sorry, I was in hurry yesterday and I haven't checked it correctly, I confirm it is already included in the repository.
