### ISSUE TITLE
unterminated quoted string

### ISSUE THREAD

**Issue by ale5000-git** [rmyorston/busybox-w32#91]
This works:
**`busybox timeout -t 1 bash -c -- "while true; do printf \".\"; done"`**

instead this:
**`busybox timeout -t 1 bash -c -- 'while true; do printf "."; done'`**

give this error:
_**`true;: line 1: syntax error: unterminated quoted string`**_

**Comment by rmyorston** [comment]
I think this is because you're running the commands from a Windows Command Prompt.  Single quotes don't group arguments together in Windows so in your second example the shell is seeing six arguments:  ```'while``` is treated as the command with ```true;```, ```do```, ```printf```, ```.;``` and ```done'```as additional, separate arguments.

Both the commands you've given work fine if run from the BusyBox shell.  You can reproduce the problem from the BusyBox shell by entering:
```
timeout -t 1 bash -c -- "'while" "true;" "do" "printf" ".;" "done'"
```
That gives the same error.

**Comment by ale5000-git** [comment]
You are right, thanks.
