### ISSUE TITLE
Source code revision of the binaries?

### ISSUE THREAD

**Issue by rgl** [rmyorston/busybox-w32#93]
Can you please describe from which git revision was a given binary produced from?

For example, the latest https://frippery.org/files/busybox/busybox-w64-FRP-1668-g236e13e3d.exe was produced from what git revision? What is the `g236e13e3d` hexadecimal string that is on the filename?

**Comment by ale5000-git** [comment]
Just look at the characters after the g: `236e13e`.

You can see the git revision [here](https://github.com/rmyorston/busybox-w32/commits/master).

**Comment by rmyorston** [comment]
ale5000-git is quite correct: the characters after the 'g' are the short form of the commit id from which the binary was built.

The other part of the string, FRP-1668 in this case, gives the number of commits since the tag 'FRP', which refers to an arbitrary commit in May 2015. The number of commits is monotonically increasing so it lets you figure out the order of the builds.  (Since the commit ids are, essentially, random they don't help with that.)

**Comment by rmyorston** [comment]
Another thought: I get the strings by running the command ```git describe --match=FRP``` in the repo at the point where I'm doing the build.

To get the string for an arbitrary commit id you can do something like:

```
$ git describe --match=FRP 236e13e3d
FRP-1668-g236e13e3d
```

**Comment by rgl** [comment]
Oh d'oh! I didn't remove the non-hexadecimal `g` character from the id... that's why I wasn't finding it anywhere. Sorry for the noise!

Good to known about that `git describe` command! thanks! :-)
